package db

var (
	// MySQL/MariaDB specific keywords
	mysqlKeywords = map[string]bool{
		// MySQL 8.0 reserved keywords (that aren't in the common list)
		"ACCESSIBLE": true, "ACCOUNT": true, "ACTION": true, "AGAINST": true,
		"AGGREGATE": true, "ALGORITHM": true, "ANALYZE": true, "ANY": true,
		"AT": true, "AUTHORS": true, "AUTO_INCREMENT": true, "AUTOEXTEND_SIZE": true,
		"AVG": true, "AVG_ROW_LENGTH": true, "BACKUP": true, "BEGIN": true,
		"BINLOG": true, "BIT": true, "BLOCK": true, "BOOL": true,
		"BOOLEAN": true, "BTREE": true, "CACHE": true, "CASCADED": true,
		"CHAIN": true, "CHANGE": true, "CHANGED": true, "CHANNEL": true,
		"CHARSET": true, "CHECKSUM": true, "CIPHER": true, "CLIENT": true,
		"COALESCE": true, "CODE": true, "COLLATE": true, "COLLATION": true,
		"COLUMNS": true, "COMMENT": true, "COMMIT": true, "COMMITTED": true,
		"COMPACT": true, "COMPLETION": true, "COMPRESSED": true, "COMPRESSION": true,
		"CONCURRENT": true, "CONNECTION": true, "CONSISTENT": true, "CONSTRAINT": true,
		"CONTAINS": true, "CONTEXT": true, "CONTRIBUTORS": true, "COPY": true,
		"CPU": true, "DATA": true, "DATAFILE": true, "DEALLOCATE": true,
		"DEFAULT": true, "DEFINER": true, "DELAY_KEY_WRITE": true, "DELAYED": true,
		"DELIMITER": true, "DES_KEY_FILE": true, "DIRECTORY": true, "DISABLE": true,
		"DISCARD": true, "DISK": true, "DO": true, "DUMPFILE": true,
		"DUPLICATE": true, "DYNAMIC": true, "ENABLE": true, "ENCLOSED": true,
		"ENCRYPTION": true, "ENGINE": true, "ENGINES": true, "ERROR": true,
		"ERRORS": true, "ESCAPE": true, "EVENT": true, "EVENTS": true,
		"EVERY": true, "EXCHANGE": true, "EXECUTE": true, "EXPANSION": true,
		"EXPIRE": true, "EXPORT": true, "EXTENDED": true, "EXTENT_SIZE": true,
		"FAST": true, "FAULTS": true, "FIELDS": true, "FILE": true,
		"FILE_BLOCK_SIZE": true, "FILTER": true, "FIRST": true, "FIXED": true,
		"FLUSH": true, "FOLLOWS": true, "FORMAT": true, "FOUND": true,
		"FULL": true, "GENERAL": true, "GEOMETRY": true, "GEOMETRYCOLLECTION": true,
		"GET_FORMAT": true, "GLOBAL": true, "GRANTS": true, "GROUP_REPLICATION": true,
		"HANDLER": true, "HASH": true, "HELP": true, "HOST": true,
		"HOSTS": true, "IDENTIFIED": true, "IGNORE": true, "IGNORE_SERVER_IDS": true,
		"IMPORT": true, "INDEXES": true, "INITIAL_SIZE": true, "INNOBASE": true,
		"INNODB": true, "IO": true, "IO_THREAD": true, "IPC": true,
		"ISOLATION": true, "ISSUER": true, "JSON": true, "KEY_BLOCK_SIZE": true,
		"LANGUAGE": true, "LAST": true, "LEAVES": true, "LESS": true,
		"LINESTRING": true, "LIST": true, "LOCAL": true, "LOGFILE": true,
		"LOGS": true, "MASTER": true, "MASTER_AUTO_POSITION": true, "MASTER_CONNECT_RETRY": true,
		"MASTER_DELAY": true, "MASTER_HEARTBEAT_PERIOD": true, "MASTER_HOST": true, "MASTER_LOG_FILE": true,
		"MASTER_LOG_POS": true, "MASTER_PASSWORD": true, "MASTER_PORT": true, "MASTER_RETRY_COUNT": true,
		"MASTER_SERVER_ID": true, "MASTER_SSL": true, "MASTER_SSL_CA": true, "MASTER_SSL_CAPATH": true,
		"MASTER_SSL_CERT": true, "MASTER_SSL_CIPHER": true, "MASTER_SSL_CRL": true, "MASTER_SSL_CRLPATH": true,
		"MASTER_SSL_KEY": true, "MASTER_SSL_VERIFY_SERVER_CERT": true, "MASTER_TLS_VERSION": true, "MASTER_USER": true,
		"MAX_CONNECTIONS_PER_HOUR": true, "MAX_QUERIES_PER_HOUR": true, "MAX_ROWS": true, "MAX_SIZE": true,
		"MAX_UPDATES_PER_HOUR": true, "MAX_USER_CONNECTIONS": true, "MEDIUM": true, "MEMORY": true,
		"MERGE": true, "MESSAGE_TEXT": true, "MICROSECOND": true, "MIGRATE": true,
		"MIN_ROWS": true, "MODE": true, "MODIFY": true, "MULTILINESTRING": true,
		"MULTIPOINT": true, "MULTIPOLYGON": true, "MUTEX": true, "MYSQL_ERRNO": true,
		"NAME": true, "NAMES": true, "NATIONAL": true, "NCHAR": true,
		"NDB": true, "NDBCLUSTER": true, "NEVER": true, "NEXT": true,
		"NO": true, "NODEGROUP": true, "NONE": true, "NOWAIT": true,
		"NO_WAIT": true, "NVARCHAR": true, "OFFSET": true, "OJ": true,
		"OLD_PASSWORD": true, "ONE": true, "ONLY": true, "OPEN": true,
		"OPTIMIZER_COSTS": true, "OPTIONS": true, "OWNER": true, "PACK_KEYS": true,
		"PAGE": true, "PARSER": true, "PARTIAL": true, "PARTITIONING": true,
		"PARTITIONS": true, "PASSWORD": true, "PHASE": true, "PLUGIN": true,
		"PLUGIN_DIR": true, "PLUGINS": true, "POINT": true, "POLYGON": true,
		"PORT": true, "PRECEDES": true, "PREPARE": true, "PRESERVE": true,
		"PREV": true, "PROCESSLIST": true, "PROFILE": true, "PROFILES": true,
		"PROXY": true, "QUERY": true, "QUICK": true, "REBUILD": true,
		"RECOVER": true, "REDO_BUFFER_SIZE": true, "REDUNDANT": true, "RELAY": true,
		"RELAYLOG": true, "RELAY_LOG_FILE": true, "RELAY_LOG_POS": true, "REMOVE": true,
		"REORGANIZE": true, "REPAIR": true, "REPEATABLE": true, "REPLICATE_DO_DB": true,
		"REPLICATE_DO_TABLE": true, "REPLICATE_IGNORE_DB": true, "REPLICATE_IGNORE_TABLE": true, "REPLICATE_REWRITE_DB": true,
		"REPLICATE_WILD_DO_TABLE": true, "REPLICATE_WILD_IGNORE_TABLE": true, "REPLICATION": true, "RESET": true,
		"RESTART": true, "RESTORE": true, "RESUME": true, "RETURNS": true,
		"ROLLBACK": true, "ROLLUP": true, "ROUTINE": true, "ROW": true,
		"ROWS": true, "ROW_FORMAT": true, "RTREE": true, "SAVEPOINT": true,
		"SCHEDULE": true, "SCHEDULER": true, "SECURITY": true, "SERIAL": true,
		"SERVER": true, "SESSION": true, "SHARE": true, "SHUTDOWN": true,
		"SIGNED": true, "SIMPLE": true, "SLAVE": true, "SLOW": true,
		"SNAPSHOT": true, "SOCKET": true, "SOME": true, "SONAME": true,
		"SOUNDS": true, "SOURCE": true, "SPATIAL": true, "SQLEXCEPTION": true,
		"SQLSTATE": true, "SQLWARNING": true, "SQL_AFTER_GTIDS": true, "SQL_AFTER_MTS_GAPS": true,
		"SQL_BEFORE_GTIDS": true, "SQL_BIG_RESULT": true, "SQL_BUFFER_RESULT": true, "SQL_CACHE": true,
		"SQL_CALC_FOUND_ROWS": true, "SQL_NO_CACHE": true, "SQL_SMALL_RESULT": true, "SQL_THREAD": true,
		"SSL": true, "STACKED": true, "STARTING": true, "STARTS": true,
		"STATS_AUTO_RECALC": true, "STATS_PERSISTENT": true, "STATS_SAMPLE_PAGES": true, "STATUS": true,
		"STOP": true, "STORAGE": true, "STORED": true, "STRAIGHT_JOIN": true,
		"STRING": true, "SUBJECT": true, "SUBPARTITION": true, "SUBPARTITIONS": true,
		"SUPER": true, "SUSPEND": true, "SWAPS": true, "SWITCHES": true,
		"TABLESPACE": true, "TEMPORARY": true, "TEMPTABLE": true, "THAN": true,
		"TRANSACTION": true, "TRUNCATE": true, "TYPE": true, "TYPES": true,
		"UNCOMMITTED": true, "UNDEFINED": true, "UNDO": true, "UNDOFILE": true,
		"UNDO_BUFFER_SIZE": true, "UNICODE": true, "UNINSTALL": true, "UNKNOWN": true,
		"UNTIL": true, "UPGRADE": true, "USAGE": true, "USE": true,
		"USER": true, "USER_RESOURCES": true, "USE_FRM": true, "VALIDATION": true,
		"VALUE": true, "VARIABLES": true, "VCPU": true, "VIEW": true,
		"VIRTUAL": true, "VISIBLE": true, "WAIT": true, "WARNINGS": true,
		"WEEK": true, "WEIGHT_STRING": true, "WITHOUT": true, "WORK": true,
		"WRAPPER": true, "X509": true, "XA": true, "XID": true,
		"XML": true, "YEAR": true,

		// MariaDB specific keywords
		"ADMIN": true, "CUME_DIST": true, "DENSE_RANK": true, "EMPTY": true,
		"EXCEPT": true, "FIRST_VALUE": true, "GROUPING": true, "INTERSECT": true,
		"JSON_TABLE": true, "LAG": true, "LAST_VALUE": true, "LEAD": true,
		"NTH_VALUE": true, "NTILE": true, "OF": true, "OVER": true,
		"PERCENT_RANK": true, "PERSIST": true, "PERSIST_ONLY": true, "PERCENT": true,
		"RANK": true, "RECURSIVE": true, "ROW_NUMBER": true, "SYSTEM": true,
		"WINDOW": true,
	}

	mariadbKeywordsCanBeUsedAsFieldNameDirectly = map[string]bool{
		// Non-reserved MariaDB/MySQL keywords - safe to use as identifiers
		"ACCOUNT":                       true,
		"ACTION":                        true,
		"ADMIN":                         true,
		"AFTER":                         true,
		"AGGREGATE":                     true,
		"ALGORITHM":                     true,
		"ANY":                           true,
		"AT":                            true,
		"AUTHORS":                       true,
		"AUTO_INCREMENT":                true,
		"AUTOEXTEND_SIZE":               true,
		"AVG":                           true,
		"AVG_ROW_LENGTH":                true,
		"BACKUP":                        true,
		"BEGIN":                         true,
		"BINLOG":                        true,
		"BIT":                           true,
		"BLOCK":                         true,
		"BOOL":                          true,
		"BOOLEAN":                       true,
		"BTREE":                         true,
		"CACHE":                         true,
		"CASCADED":                      true,
		"CHAIN":                         true,
		"CHANGE":                        true,
		"CHANGED":                       true,
		"CHANNEL":                       true,
		"CHARSET":                       true,
		"CHECKSUM":                      true,
		"CIPHER":                        true,
		"CLIENT":                        true,
		"COALESCE":                      true,
		"CODE":                          true,
		"COLLATION":                     true,
		"COLUMNS":                       true,
		"COMMENT":                       true,
		"COMMIT":                        true,
		"COMMITTED":                     true,
		"COMPACT":                       true,
		"COMPLETION":                    true,
		"COMPRESSED":                    true,
		"COMPRESSION":                   true,
		"CONCURRENT":                    true,
		"CONNECTION":                    true,
		"CONSISTENT":                    true,
		"CONTAINS":                      true,
		"CONTEXT":                       true,
		"CONTRIBUTORS":                  true,
		"COPY":                          true,
		"CPU":                           true,
		"DATA":                          true,
		"DATAFILE":                      true,
		"DEALLOCATE":                    true,
		"DEFINER":                       true,
		"DELAY_KEY_WRITE":               true,
		"DELAYED":                       true,
		"DELIMITER":                     true,
		"DES_KEY_FILE":                  true,
		"DIRECTORY":                     true,
		"DISABLE":                       true,
		"DISCARD":                       true,
		"DISK":                          true,
		"DO":                            true,
		"DUMPFILE":                      true,
		"DUPLICATE":                     true,
		"DYNAMIC":                       true,
		"ENABLE":                        true,
		"ENCLOSED":                      true,
		"ENCRYPTION":                    true,
		"ENGINE":                        true,
		"ENGINES":                       true,
		"ERROR":                         true,
		"ERRORS":                        true,
		"ESCAPE":                        true,
		"EVENT":                         true,
		"EVENTS":                        true,
		"EVERY":                         true,
		"EXCHANGE":                      true,
		"EXECUTE":                       true,
		"EXPANSION":                     true,
		"EXPIRE":                        true,
		"EXPORT":                        true,
		"EXTENDED":                      true,
		"EXTENT_SIZE":                   true,
		"FAST":                          true,
		"FAULTS":                        true,
		"FIELDS":                        true,
		"FILE":                          true,
		"FILE_BLOCK_SIZE":               true,
		"FILTER":                        true,
		"FIRST":                         true,
		"FIXED":                         true,
		"FLUSH":                         true,
		"FOLLOWS":                       true,
		"FORMAT":                        true,
		"FOUND":                         true,
		"GENERAL":                       true,
		"GEOMETRY":                      true,
		"GEOMETRYCOLLECTION":            true,
		"GET_FORMAT":                    true,
		"GLOBAL":                        true,
		"GRANTS":                        true,
		"GROUP_REPLICATION":             true,
		"HANDLER":                       true,
		"HASH":                          true,
		"HELP":                          true,
		"HOST":                          true,
		"HOSTS":                         true,
		"IDENTIFIED":                    true,
		"IGNORE_SERVER_IDS":             true,
		"IMPORT":                        true,
		"INDEXES":                       true,
		"INITIAL_SIZE":                  true,
		"INNOBASE":                      true,
		"INNODB":                        true,
		"IO":                            true,
		"IO_THREAD":                     true,
		"IPC":                           true,
		"ISOLATION":                     true,
		"ISSUER":                        true,
		"JSON":                          true,
		"KEY_BLOCK_SIZE":                true,
		"LANGUAGE":                      true,
		"LAST":                          true,
		"LEAVES":                        true,
		"LESS":                          true,
		"LINESTRING":                    true,
		"LIST":                          true,
		"LOCAL":                         true,
		"LOGFILE":                       true,
		"LOGS":                          true,
		"MASTER":                        true,
		"MASTER_AUTO_POSITION":          true,
		"MASTER_CONNECT_RETRY":          true,
		"MASTER_DELAY":                  true,
		"MASTER_HEARTBEAT_PERIOD":       true,
		"MASTER_HOST":                   true,
		"MASTER_LOG_FILE":               true,
		"MASTER_LOG_POS":                true,
		"MASTER_PASSWORD":               true,
		"MASTER_PORT":                   true,
		"MASTER_RETRY_COUNT":            true,
		"MASTER_SERVER_ID":              true,
		"MASTER_SSL":                    true,
		"MASTER_SSL_CA":                 true,
		"MASTER_SSL_CAPATH":             true,
		"MASTER_SSL_CERT":               true,
		"MASTER_SSL_CIPHER":             true,
		"MASTER_SSL_CRL":                true,
		"MASTER_SSL_CRLPATH":            true,
		"MASTER_SSL_KEY":                true,
		"MASTER_SSL_VERIFY_SERVER_CERT": true,
		"MASTER_TLS_VERSION":            true,
		"MASTER_USER":                   true,
		"MAX_CONNECTIONS_PER_HOUR":      true,
		"MAX_QUERIES_PER_HOUR":          true,
		"MAX_ROWS":                      true,
		"MAX_SIZE":                      true,
		"MAX_UPDATES_PER_HOUR":          true,
		"MAX_USER_CONNECTIONS":          true,
		"MEDIUM":                        true,
		"MEMORY":                        true,
		"MERGE":                         true,
		"MESSAGE_TEXT":                  true,
		"MICROSECOND":                   true,
		"MIGRATE":                       true,
		"MIN_ROWS":                      true,
		"MODE":                          true,
		"MODIFY":                        true,
		"MULTILINESTRING":               true,
		"MULTIPOINT":                    true,
		"MULTIPOLYGON":                  true,
		"MUTEX":                         true,
		"MYSQL_ERRNO":                   true,
		"NAME":                          true,
		"NAMES":                         true,
		"NATIONAL":                      true,
		"NCHAR":                         true,
		"NDB":                           true,
		"NDBCLUSTER":                    true,
		"NEVER":                         true,
		"NEXT":                          true,
		"NO":                            true,
		"NODEGROUP":                     true,
		"NONE":                          true,
		"NOWAIT":                        true,
		"NO_WAIT":                       true,
		"NVARCHAR":                      true,
		"OFFSET":                        true,
		"OJ":                            true,
		"OLD_PASSWORD":                  true,
		"ONE":                           true,
		"ONLY":                          true,
		"OPEN":                          true,
		"OPTIMIZER_COSTS":               true,
		"OPTIONS":                       true,
		"OWNER":                         true,
		"PACK_KEYS":                     true,
		"PAGE":                          true,
		"PARSER":                        true,
		"PARTIAL":                       true,
		"PARTITIONING":                  true,
		"PARTITIONS":                    true,
		"PASSWORD":                      true,
		"PHASE":                         true,
		"PLUGIN":                        true,
		"PLUGIN_DIR":                    true,
		"PLUGINS":                       true,
		"POINT":                         true,
		"POLYGON":                       true,
		"PORT":                          true,
		"PRECEDES":                      true,
		"PREPARE":                       true,
		"PRESERVE":                      true,
		"PREV":                          true,
		"PROCESSLIST":                   true,
		"PROFILE":                       true,
		"PROFILES":                      true,
		"PROXY":                         true,
		"QUERY":                         true,
		"QUICK":                         true,
		"REBUILD":                       true,
		"RECOVER":                       true,
		"REDO_BUFFER_SIZE":              true,
		"REDUNDANT":                     true,
		"RELAY":                         true,
		"RELAYLOG":                      true,
		"RELAY_LOG_FILE":                true,
		"RELAY_LOG_POS":                 true,
		"REMOVE":                        true,
		"REORGANIZE":                    true,
		"REPAIR":                        true,
		"REPEATABLE":                    true,
		"REPLICATE_DO_DB":               true,
		"REPLICATE_DO_TABLE":            true,
		"REPLICATE_IGNORE_DB":           true,
		"REPLICATE_IGNORE_TABLE":        true,
		"REPLICATE_REWRITE_DB":          true,
		"REPLICATE_WILD_DO_TABLE":       true,
		"REPLICATE_WILD_IGNORE_TABLE":   true,
		"REPLICATION":                   true,
		"RESET":                         true,
		"RESTART":                       true,
		"RESTORE":                       true,
		"RESUME":                        true,
		"RETURNS":                       true,
		"ROLLBACK":                      true,
		"ROLLUP":                        true,
		"ROUTINE":                       true,
		"ROW":                           true,
		"ROWS":                          true,
		"ROW_FORMAT":                    true,
		"RTREE":                         true,
		"SAVEPOINT":                     true,
		"SCHEDULE":                      true,
		"SCHEDULER":                     true,
		"SECURITY":                      true,
		"SERIAL":                        true,
		"SERVER":                        true,
		"SESSION":                       true,
		"SHARE":                         true,
		"SHUTDOWN":                      true,
		"SIGNED":                        true,
		"SIMPLE":                        true,
		"SLAVE":                         true,
		"SLOW":                          true,
		"SNAPSHOT":                      true,
		"SOCKET":                        true,
		"SOME":                          true,
		"SONAME":                        true,
		"SOUNDS":                        true,
		"SOURCE":                        true,
		"SPATIAL":                       true,
		"SQLEXCEPTION":                  true,
		"SQLSTATE":                      true,
		"SQLWARNING":                    true,
		"SQL_AFTER_GTIDS":               true,
		"SQL_AFTER_MTS_GAPS":            true,
		"SQL_BEFORE_GTIDS":              true,
		"SQL_BIG_RESULT":                true,
		"SQL_BUFFER_RESULT":             true,
		"SQL_CACHE":                     true,
		"SQL_CALC_FOUND_ROWS":           true,
		"SQL_NO_CACHE":                  true,
		"SQL_SMALL_RESULT":              true,
		"SQL_THREAD":                    true,
		"SSL":                           true,
		"STACKED":                       true,
		"STARTING":                      true,
		"STARTS":                        true,
		"STATS_AUTO_RECALC":             true,
		"STATS_PERSISTENT":              true,
		"STATS_SAMPLE_PAGES":            true,
		"STATUS":                        true,
		"STOP":                          true,
		"STORAGE":                       true,
		"STORED":                        true,
		"STRING":                        true,
		"SUBJECT":                       true,
		"SUBPARTITION":                  true,
		"SUBPARTITIONS":                 true,
		"SUPER":                         true,
		"SUSPEND":                       true,
		"SWAPS":                         true,
		"SWITCHES":                      true,
		"TABLESPACE":                    true,
		"TEMPORARY":                     true,
		"TEMPTABLE":                     true,
		"THAN":                          true,
		"TRANSACTION":                   true,
		"TRUNCATE":                      true,
		"TYPE":                          true,
		"TYPES":                         true,
		"UNCOMMITTED":                   true,
		"UNDEFINED":                     true,
		"UNDO":                          true,
		"UNDOFILE":                      true,
		"UNDO_BUFFER_SIZE":              true,
		"UNICODE":                       true,
		"UNINSTALL":                     true,
		"UNKNOWN":                       true,
		"UNTIL":                         true,
		"UPGRADE":                       true,
		"USAGE":                         true,
		"USE":                           true,
		"USER_RESOURCES":                true,
		"USE_FRM":                       true,
		"VALIDATION":                    true,
		"VALUE":                         true,
		"VARIABLES":                     true,
		"VCPU":                          true,
		"VIRTUAL":                       true,
		"VISIBLE":                       true,
		"WAIT":                          true,
		"WARNINGS":                      true,
		"WEEK":                          true,
		"WEIGHT_STRING":                 true,
		"WITHOUT":                       true,
		"WORK":                          true,
		"WRAPPER":                       true,
		"X509":                          true,
		"XA":                            true,
		"XID":                           true,
		"XML":                           true,
		"YEAR":                          true,
		// MariaDB specific non-reserved keywords
		"CUME_DIST":    true,
		"DENSE_RANK":   true,
		"EMPTY":        true,
		"FIRST_VALUE":  true,
		"GROUPING":     true,
		"JSON_TABLE":   true,
		"LAG":          true,
		"LAST_VALUE":   true,
		"LEAD":         true,
		"NTH_VALUE":    true,
		"NTILE":        true,
		"OF":           true,
		"OVER":         true,
		"PERCENT_RANK": true,
		"PERSIST":      true,
		"PERSIST_ONLY": true,
		"PERCENT":      true,
		"RANK":         true,
		"RECURSIVE":    true,
		"ROW_NUMBER":   true,
		"SYSTEM":       true,
	}
)
