package db

var (
	// Oracle specific keywords
	oracleKeywords = map[string]bool{
		// Oracle specific reserved keywords (that aren't in the common list)
		"ACCESS": true, "ACCOUNT": true, "ACTIVATE": true, "ADMIN": true,
		"ADMINISTRATOR": true, "ADVISE": true, "AFTER": true, "ALGORITHM": true,
		"ALLOCATE": true, "ANALYZE": true, "ARCHIVE": true, "ARCHIVELOG": true,
		"ARRAY": true, "ASSOCIATE": true, "AT": true, "ATTRIBUTE": true,
		"AUDIT": true, "AUTHENTICATED": true, "AUTHORIZATION": true, "AUTOALLOCATE": true,
		"AUTOEXTEND": true, "AUTOMATIC": true, "AVAILABILITY": true, "BACKUP": true,
		"BECOME": true, "BEFORE": true, "BEGIN": true, "BEHALF": true,
		"BINARY": true, "BINDING": true, "BITMAP": true, "BLOCK": true,
		"BLOCKSIZE": true, "BODY": true, "CACHE": true, "CACHE_INSTANCES": true,
		"CANCEL": true, "CASCADE": true, "CATEGORY": true, "CERTIFICATE": true,
		"CHAINED": true, "CHANGE": true, "CHAR_CS": true, "CHARACTER": true,
		"CHECKPOINT": true, "CHILD": true, "CHUNK": true, "CLASS": true,
		"CLEAR": true, "CLONE": true, "CLOSE": true, "CLUSTER": true,
		"COMMENT": true, "COMMIT": true, "COMMITTED": true, "COMPATIBILITY": true,
		"COMPILE": true, "COMPLETE": true, "COMPOSITE_LIMIT": true, "COMPRESS": true,
		"COMPUTE": true, "CONNECT": true, "CONNECT_TIME": true, "CONSIDER": true,
		"CONSISTENT": true, "CONSTRAINT": true, "CONTAINER": true, "CONTAINED": true,
		"CONTINUE": true, "CONTROLFILE": true, "CORRUPTION": true, "COST": true,
		"CPU_PER_CALL": true, "CPU_PER_SESSION": true, "CURRENT": true, "CURRENT_USER": true,
		"CURSOR": true, "CYCLE": true, "DANGLING": true, "DATABASE": true,
		"DATAFILE": true, "DATAFILES": true, "DATAOBJNO": true, "DBA": true,
		"DBHIGH": true, "DBLOW": true, "DBMAC": true, "DDL": true,
		"DEALLOCATE": true, "DEBUG": true, "DEFINE": true, "DEFINITION": true,
		"DEGREE": true, "DEREF": true, "DIRECT_LOAD": true, "DIRECTORY": true,
		"DISABLE": true, "DISASSOCIATE": true, "DISCONNECT": true, "DISK": true,
		"DISKGROUP": true, "DISKS": true, "DISMOUNT": true, "DISPATCHERS": true,
		"DISTRIBUTED": true, "DML": true, "DOCUMENT": true, "DOMAIN": true,
		"DUMP": true, "EDIT_DISTANCE": true, "EDITION": true, "ELEMENT": true,
		"ELIMINATE_DUPLICATES": true, "ENABLE": true, "ENCRYPTION": true, "ENFORCE": true,
		"ENTRY": true, "ERROR_ON_OVERLAP_TIME": true, "ERRORS": true, "ESCAPE": true,
		"ESTIMATE": true, "EVENTS": true, "EXCEPT": true, "EXCEPTIONS": true,
		"EXCHANGE": true, "EXCLUDING": true, "EXCLUSIVE": true, "EXECUTE": true,
		"EXPIRE": true, "EXPLAIN": true, "EXTENT": true, "EXTENTS": true,
		"EXTERNALLY": true, "FAILED_LOGIN_ATTEMPTS": true, "FAST": true, "FEATURE": true,
		"FILE": true, "FILESYSTEM_LIKE_LOGGING": true, "FINAL": true, "FINISH": true,
		"FIRST": true, "FLUSH": true, "FOLLOWING": true, "FORCE": true,
		"FOREIGN": true, "FREELIST": true, "FREELISTS": true, "FREEPOOLS": true,
		"FRESH": true, "FULL": true, "FUNCTION": true, "FUNCTIONS": true,
		"GENERATED": true, "GLOBAL": true, "GLOBAL_NAME": true, "GLOBALLY": true,
		"GROUPS": true, "GUARANTEED": true, "GUARD": true, "HASH": true,
		"HASHKEYS": true, "HEADER": true, "HEAP": true, "HIERARCHY": true,
		"HOUR": true, "IDENTIFIED": true, "IDENTIFIER": true, "IDENTITY": true,
		"IDGENERATORS": true, "IDLE_TIME": true, "IMMEDIATE": true, "IMPLEMENTATION": true,
		"INCLUDING": true, "INCREMENT": true, "INCREMENTAL": true, "INDEXTYPES": true,
		"INDICATOR": true, "INITIAL": true, "INITIALIZED": true, "INITIALLY": true,
		"INITRANS": true, "INSTANCE": true, "INSTANCES": true, "INSTANTIABLE": true,
		"INSTEAD": true, "INTERMEDIATE": true, "ISOLATION": true, "JAVA": true,
		"JOB": true, "KEEP": true, "KEY": true, "KEYS": true,
		"KEYSIZE": true, "LABEL": true, "LANGUAGE": true, "LAST": true,
		"LAYER": true, "LDAP_REG_SYNC_INTERVAL": true, "LDAP_REGISTRATION": true, "LDAP_REGISTRATION_ENABLED": true,
		"LEADING": true, "LEVEL": true, "LIBRARY": true, "LIMIT": true,
		"LINK": true, "LIST": true, "LOB": true, "LOCAL": true,
		"LOCATION": true, "LOCATOR": true, "LOCK": true, "LOCKED": true,
		"LOG": true, "LOGFILE": true, "LOGGING": true, "LOGICAL": true,
		"LOGICAL_READS_PER_CALL": true, "LOGICAL_READS_PER_SESSION": true, "LOGON": true, "MANAGE": true,
		"MANAGED": true, "MANAGEMENT": true, "MANUAL": true, "MAP": true,
		"MAPPING": true, "MASTER": true, "MATCHED": true, "MATERIALIZED": true,
		"MAXARCHLOGS": true, "MAXDATAFILES": true, "MAXEXTENTS": true, "MAXIMIZE": true,
		"MAXINSTANCES": true, "MAXLOGFILES": true, "MAXLOGHISTORY": true, "MAXLOGMEMBERS": true,
		"MAXSIZE": true, "MAXTRANS": true, "MAXVALUE": true, "MEMBER": true,
		"MEMORY": true, "MERGE": true, "MINEXTENTS": true, "MINIMIZE": true,
		"MINIMUM": true, "MINVALUE": true, "MINUTE": true, "MLSLABEL": true,
		"MODE": true, "MODIFY": true, "MONITORING": true, "MONTH": true,
		"MOUNT": true, "MOVE": true, "MOVEMENT": true, "MULTISET": true,
		"NAME": true, "NAMED": true, "NAMESPACE": true, "NAN": true,
		"NATIONAL": true, "NCHAR": true, "NCHAR_CS": true, "NCLOB": true,
		"NEEDED": true, "NESTED": true, "NETWORK": true, "NEW": true,
		"NEXT": true, "NO": true, "NOARCHIVELOG": true, "NOAUDIT": true,
		"NOCACHE": true, "NOCOMPRESS": true, "NOCYCLE": true, "NODELAY": true,
		"NOFORCE": true, "NOLOGGING": true, "NOMAPPING": true, "NOMAXVALUE": true,
		"NOMINIMIZE": true, "NOMINVALUE": true, "NOMONITORING": true, "NONE": true,
		"NOPARALLEL": true, "NORELY": true, "NOREVERSE": true, "NORMAL": true,
		"NOROWDEPENDENCIES": true, "NOSORT": true, "NOTHING": true, "NOVALIDATE": true,
		"NULLS": true, "OBJECT": true, "OFF": true, "OFFLINE": true,
		"OID": true, "OIDINDEX": true, "OLD": true, "ONLINE": true,
		"ONLY": true, "OPCODE": true, "OPEN": true, "OPERATOR": true,
		"OPTIMAL": true, "OPTION": true, "ORGANIZATION": true, "OUT": true,
		"OUTER": true, "OUTLINE": true, "OVERFLOW": true, "OVERRIDING": true,
		"PACKAGE": true, "PACKAGES": true, "PARALLEL": true, "PARALLEL_ENABLE": true,
		"PARAMETERS": true, "PARENT": true, "PARTITION": true, "PARTITIONS": true,
		"PASSWORD": true, "PASSWORD_GRACE_TIME": true, "PASSWORD_LIFE_TIME": true, "PASSWORD_LOCK_TIME": true,
		"PASSWORD_REUSE_MAX": true, "PASSWORD_REUSE_TIME": true, "PASSWORD_VERIFY_FUNCTION": true, "PATH": true,
		"PCTFREE": true, "PCTINCREASE": true, "PCTTHRESHOLD": true, "PCTUSED": true,
		"PCTVERSION": true, "PERCENT_RANK": true, "PERFORMANCE": true, "PERMANENT": true,
		"PFILE": true, "PHYSICAL": true, "PIV_GB": true, "PIV_SSF": true,
		"PLAN": true, "PLSQL_CCFLAGS": true, "PLSQL_CODE_TYPE": true, "PLSQL_DEBUG": true,
		"PLSQL_OPTIMIZE_LEVEL": true, "PLSQL_WARNINGS": true, "POLICY": true, "POST_TRANSACTION": true,
		"POWER": true, "PRAGMA": true, "PREBUILT": true, "PRECEDING": true,
		"PRESERVE": true, "PRESERVE_OID": true, "PRIMARY": true, "PRIOR": true,
		"PRIVATE": true, "PRIVATE_SGA": true, "PRIVILEGE": true, "PRIVILEGES": true,
		"PROCEDURE": true, "PROFILE": true, "PROGRAM": true, "PROJECT": true,
		"PROTECTED": true, "PROTECTION": true, "PUBLIC": true, "PURGE": true,
		"QUERY": true, "QUIESCE": true, "QUOTA": true, "RANDOM": true,
		"RANGE": true, "RAW": true, "READ": true, "READS": true,
		"REBUILD": true, "RECORDS_PER_BLOCK": true, "RECOVER": true, "RECOVERY": true,
		"RECYCLEBIN": true, "REDUCED": true, "REDUNDANCY": true, "REF": true,
		"REFERENCE": true, "REFERENCED": true, "REFERENCES": true, "REFERENCING": true,
		"REFRESH": true, "REGISTER": true, "REGISTERED": true, "REJECT": true,
		"RELY": true, "REMOTE_DEPENDENCIES_MODE": true, "RENAME": true, "REPAIR": true,
		"REPLACE": true, "REQUIRED": true, "RESET": true, "RESETLOGS": true,
		"RESIZE": true, "RESOLVE": true, "RESOLVER": true, "RESOURCE": true,
		"RESTRICT": true, "RESTRICTED": true, "RESUMABLE": true, "RESUME": true,
		"RETENTION": true, "RETURN": true, "RETURNING": true, "REUSE": true,
		"REVERSE": true, "REVOKE": true, "REWRITE": true, "ROLE": true,
		"ROLES": true, "ROLLBACK": true, "ROLLUP": true, "ROW": true,
		"ROWDEPENDENCIES": true, "ROWID": true, "ROWNUM": true, "ROWS": true,
		"RULE": true, "SAMPLE": true, "SAVEPOINT": true, "SCAN": true,
		"SCAN_INSTANCES": true, "SCHEDULER": true, "SCHEMA": true, "SCN": true,
		"SCOPE": true, "SECOND": true, "SECURITY": true, "SEGMENT": true,
		"SELF": true, "SEQUENCE": true, "SERIALIZABLE": true, "SESSION": true,
		"SESSIONS_PER_USER": true, "SHARE": true, "SHARED": true, "SHARED_POOL": true,
		"SHRINK": true, "SHUTDOWN": true, "SIBLINGS": true, "SINGLE": true,
		"SIZE": true, "SKIP": true, "SORT": true, "SOURCE": true,
		"SPACE": true, "SPECIFICATION": true, "SPFILE": true, "SPLIT": true,
		"STANDBY": true, "START": true, "STATEMENT_ID": true, "STATIC": true,
		"STATISTICS": true, "STOP": true, "STORAGE": true, "STORE": true,
		"STRUCTURE": true, "SUBMULTISET": true, "SUBPARTITION": true, "SUBPARTITIONS": true,
		"SUBSTITUTABLE": true, "SUBTYPE": true, "SUCCESS": true, "SUSPEND": true,
		"SWITCH": true, "SWITCHOVER": true, "SYS_OP_BITVEC": true, "SYS_OP_ENFORCE_NOT_NULL$": true,
		"SYS_OP_NTCIMG$": true, "SYNONYM": true, "SYSDATE": true, "SYSDBA": true,
		"SYSOPER": true, "SYSTEM": true, "TABLES": true, "TABLESPACE": true,
		"TEMPFILE": true, "TEMPORARY": true, "TEMPORARY_TABLESPACE": true, "TERMINATE": true,
		"THREAD": true, "THROUGH": true, "TIES": true, "TIME": true,
		"TIMEOUT": true, "TIMEZONE_ABBR": true, "TIMEZONE_HOUR": true, "TIMEZONE_MINUTE": true,
		"TIMEZONE_REGION": true, "TRACE": true, "TRANSACTION": true, "TRANSITIONAL": true,
		"TRIGGERS": true, "TRUNCATE": true, "TRUSTED": true, "TUNING": true,
		"TX": true, "TYPE": true, "TYPES": true, "UID": true,
		"UNARCHIVED": true, "UNBOUNDED": true, "UNDEFINE": true, "UNDER": true,
		"UNDO": true, "UNDROP": true, "UNIFORM": true, "UNLIMITED": true,
		"UNLOCK": true, "UNPACKED": true, "UNPROTECTED": true, "UNQUIESCE": true,
		"UNRECOVERABLE": true, "UNTIL": true, "UNUSABLE": true, "UNUSED": true,
		"UPDATABLE": true, "UPGRADE": true, "USAGE": true, "USE": true,
		"USING": true, "VALIDATE": true, "VALIDATION": true, "VALUE": true,
		"VARRAY": true, "VARYING": true, "VERIFY": true, "VIRTUAL": true,
		"VISIBLE": true, "WAIT": true, "WALLET": true, "WELLFORMED": true,
		"WORK": true, "WRAPPED": true, "WRITE": true, "XMLATTRIBUTES": true,
		"XMLCOLATTVAL": true, "XMLELEMENT": true, "XMLFOREST": true, "XMLPARSE": true,
		"XMLROOT": true, "XMLSCHEMA": true, "XMLSERIALIZE": true, "XMLTABLE": true,
		"XMLTYPE": true, "YEAR": true, "YES": true, "ZONE": true,
	}

	// oracleKeywordsCanBeUsedAsFieldNameDirectly contains Oracle keywords that are
	// non-reserved and can be used as column/table names without double quotes.
	// Based on Oracle Database official documentation
	oracleKeywordsCanBeUsedAsFieldNameDirectly = map[string]bool{
		// Non-reserved Oracle keywords - safe to use as identifiers
		"ACCOUNT":                   true,
		"ACTIVATE":                  true,
		"ADMIN":                     true,
		"ADMINISTRATOR":             true,
		"ADVISE":                    true,
		"AFTER":                     true,
		"ALGORITHM":                 true,
		"ANALYZE":                   true,
		"ARCHIVE":                   true,
		"ARCHIVELOG":                true,
		"ASSOCIATE":                 true,
		"AT":                        true,
		"ATTRIBUTE":                 true,
		"AUDIT":                     true,
		"AUTHENTICATED":             true,
		"AUTOALLOCATE":              true,
		"AUTOEXTEND":                true,
		"AUTOMATIC":                 true,
		"AVAILABILITY":              true,
		"BACKUP":                    true,
		"BECOME":                    true,
		"BEFORE":                    true,
		"BEGIN":                     true,
		"BEHALF":                    true,
		"BINDING":                   true,
		"BITMAP":                    true,
		"BLOCK":                     true,
		"BLOCKSIZE":                 true,
		"BODY":                      true,
		"CACHE":                     true,
		"CACHE_INSTANCES":           true,
		"CANCEL":                    true,
		"CATEGORY":                  true,
		"CERTIFICATE":               true,
		"CHAINED":                   true,
		"CHANGE":                    true,
		"CHAR_CS":                   true,
		"CHECKPOINT":                true,
		"CHILD":                     true,
		"CHUNK":                     true,
		"CLASS":                     true,
		"CLEAR":                     true,
		"CLONE":                     true,
		"CLOSE":                     true,
		"COMMENT":                   true,
		"COMMIT":                    true,
		"COMMITTED":                 true,
		"COMPATIBILITY":             true,
		"COMPILE":                   true,
		"COMPLETE":                  true,
		"COMPOSITE_LIMIT":           true,
		"COMPRESS":                  true,
		"COMPUTE":                   true,
		"CONNECT_TIME":              true,
		"CONSIDER":                  true,
		"CONSISTENT":                true,
		"CONTAINER":                 true,
		"CONTAINED":                 true,
		"CONTINUE":                  true,
		"CONTROLFILE":               true,
		"CORRUPTION":                true,
		"COST":                      true,
		"CPU_PER_CALL":              true,
		"CPU_PER_SESSION":           true,
		"CURSOR":                    true,
		"CYCLE":                     true,
		"DANGLING":                  true,
		"DATAFILE":                  true,
		"DATAFILES":                 true,
		"DATAOBJNO":                 true,
		"DBA":                       true,
		"DBHIGH":                    true,
		"DBLOW":                     true,
		"DBMAC":                     true,
		"DDL":                       true,
		"DEALLOCATE":                true,
		"DEBUG":                     true,
		"DEFINE":                    true,
		"DEFINITION":                true,
		"DEGREE":                    true,
		"DEREF":                     true,
		"DIRECT_LOAD":               true,
		"DIRECTORY":                 true,
		"DISABLE":                   true,
		"DISASSOCIATE":              true,
		"DISCONNECT":                true,
		"DISK":                      true,
		"DISKGROUP":                 true,
		"DISKS":                     true,
		"DISMOUNT":                  true,
		"DISPATCHERS":               true,
		"DISTRIBUTED":               true,
		"DML":                       true,
		"DOCUMENT":                  true,
		"DOMAIN":                    true,
		"DUMP":                      true,
		"EDIT_DISTANCE":             true,
		"EDITION":                   true,
		"ELEMENT":                   true,
		"ELIMINATE_DUPLICATES":      true,
		"ENABLE":                    true,
		"ENCRYPTION":                true,
		"ENFORCE":                   true,
		"ENTRY":                     true,
		"ERROR_ON_OVERLAP_TIME":     true,
		"ERRORS":                    true,
		"ESCAPE":                    true,
		"ESTIMATE":                  true,
		"EVENTS":                    true,
		"EXCEPTIONS":                true,
		"EXCHANGE":                  true,
		"EXCLUDING":                 true,
		"EXCLUSIVE":                 true,
		"EXECUTE":                   true,
		"EXPIRE":                    true,
		"EXPLAIN":                   true,
		"EXTENT":                    true,
		"EXTENTS":                   true,
		"EXTERNALLY":                true,
		"FAILED_LOGIN_ATTEMPTS":     true,
		"FAST":                      true,
		"FEATURE":                   true,
		"FILE":                      true,
		"FILESYSTEM_LIKE_LOGGING":   true,
		"FINAL":                     true,
		"FINISH":                    true,
		"FIRST":                     true,
		"FLUSH":                     true,
		"FOLLOWING":                 true,
		"FORCE":                     true,
		"FREELIST":                  true,
		"FREELISTS":                 true,
		"FREEPOOLS":                 true,
		"FRESH":                     true,
		"FUNCTIONS":                 true,
		"GENERATED":                 true,
		"GLOBAL":                    true,
		"GLOBAL_NAME":               true,
		"GLOBALLY":                  true,
		"GROUPS":                    true,
		"GUARANTEED":                true,
		"GUARD":                     true,
		"HASH":                      true,
		"HASHKEYS":                  true,
		"HEADER":                    true,
		"HEAP":                      true,
		"HIERARCHY":                 true,
		"HOUR":                      true,
		"IDENTIFIED":                true,
		"IDENTIFIER":                true,
		"IDGENERATORS":              true,
		"IDLE_TIME":                 true,
		"IMMEDIATE":                 true,
		"IMPLEMENTATION":            true,
		"INCLUDING":                 true,
		"INCREMENT":                 true,
		"INCREMENTAL":               true,
		"INDEXTYPES":                true,
		"INDICATOR":                 true,
		"INITIAL":                   true,
		"INITIALIZED":               true,
		"INITIALLY":                 true,
		"INITRANS":                  true,
		"INSTANCE":                  true,
		"INSTANCES":                 true,
		"INSTANTIABLE":              true,
		"INSTEAD":                   true,
		"INTERMEDIATE":              true,
		"ISOLATION":                 true,
		"JAVA":                      true,
		"JOB":                       true,
		"KEEP":                      true,
		"KEY":                       true,
		"KEYS":                      true,
		"KEYSIZE":                   true,
		"LABEL":                     true,
		"LANGUAGE":                  true,
		"LAST":                      true,
		"LAYER":                     true,
		"LDAP_REG_SYNC_INTERVAL":    true,
		"LDAP_REGISTRATION":         true,
		"LDAP_REGISTRATION_ENABLED": true,
		"LEADING":                   true,
		"LEVEL":                     true,
		"LIBRARY":                   true,
		"LINK":                      true,
		"LIST":                      true,
		"LOB":                       true,
		"LOCAL":                     true,
		"LOCATION":                  true,
		"LOCATOR":                   true,
		"LOCK":                      true,
		"LOCKED":                    true,
		"LOG":                       true,
		"LOGFILE":                   true,
		"LOGGING":                   true,
		"LOGICAL":                   true,
		"LOGICAL_READS_PER_CALL":    true,
		"LOGICAL_READS_PER_SESSION": true,
		"LOGON":                     true,
		"MANAGE":                    true,
		"MANAGED":                   true,
		"MANAGEMENT":                true,
		"MANUAL":                    true,
		"MAP":                       true,
		"MAPPING":                   true,
		"MASTER":                    true,
		"MATCHED":                   true,
		"MATERIALIZED":              true,
		"MAXARCHLOGS":               true,
		"MAXDATAFILES":              true,
		"MAXEXTENTS":                true,
		"MAXIMIZE":                  true,
		"MAXINSTANCES":              true,
		"MAXLOGFILES":               true,
		"MAXLOGHISTORY":             true,
		"MAXLOGMEMBERS":             true,
		"MAXSIZE":                   true,
		"MAXTRANS":                  true,
		"MAXVALUE":                  true,
		"MEMBER":                    true,
		"MEMORY":                    true,
		"MINEXTENTS":                true,
		"MINIMIZE":                  true,
		"MINIMUM":                   true,
		"MINVALUE":                  true,
		"MINUTE":                    true,
		"MLSLABEL":                  true,
		"MODE":                      true,
		"MODIFY":                    true,
		"MONITORING":                true,
		"MONTH":                     true,
		"MOUNT":                     true,
		"MOVE":                      true,
		"MOVEMENT":                  true,
		"MULTISET":                  true,
		"NAME":                      true,
		"NAMED":                     true,
		"NAMESPACE":                 true,
		"NAN":                       true,
		"NATIONAL":                  true,
		"NCHAR":                     true,
		"NCHAR_CS":                  true,
		"NCLOB":                     true,
		"NEEDED":                    true,
		"NESTED":                    true,
		"NETWORK":                   true,
		"NEW":                       true,
		"NEXT":                      true,
		"NO":                        true,
		"NOARCHIVELOG":              true,
		"NOAUDIT":                   true,
		"NOCACHE":                   true,
		"NOCOMPRESS":                true,
		"NOCYCLE":                   true,
		"NODELAY":                   true,
		"NOFORCE":                   true,
		"NOLOGGING":                 true,
		"NOMAPPING":                 true,
		"NOMAXVALUE":                true,
		"NOMINIMIZE":                true,
		"NOMINVALUE":                true,
		"NOMONITORING":              true,
		"NONE":                      true,
		"NOPARALLEL":                true,
		"NORELY":                    true,
		"NOREVERSE":                 true,
		"NORMAL":                    true,
		"NOROWDEPENDENCIES":         true,
		"NOSORT":                    true,
		"NOTHING":                   true,
		"NOVALIDATE":                true,
		"NULLS":                     true,
		"OBJECT":                    true,
		"OFF":                       true,
		"OFFLINE":                   true,
		"OID":                       true,
		"OIDINDEX":                  true,
		"OLD":                       true,
		"ONLINE":                    true,
		"ONLY":                      true,
		"OPCODE":                    true,
		"OPEN":                      true,
		"OPERATOR":                  true,
		"OPTIMAL":                   true,
		"OPTION":                    true,
		"ORGANIZATION":              true,
		"OUT":                       true,
		"OUTLINE":                   true,
		"OVERFLOW":                  true,
		"OVERRIDING":                true,
		"PACKAGE":                   true,
		"PACKAGES":                  true,
		"PARALLEL":                  true,
		"PARALLEL_ENABLE":           true,
		"PARAMETERS":                true,
		"PARENT":                    true,
		"PARTITION":                 true,
		"PARTITIONS":                true,
		"PASSWORD":                  true,
		"PASSWORD_GRACE_TIME":       true,
		"PASSWORD_LIFE_TIME":        true,
		"PASSWORD_LOCK_TIME":        true,
		"PASSWORD_REUSE_MAX":        true,
		"PASSWORD_REUSE_TIME":       true,
		"PASSWORD_VERIFY_FUNCTION":  true,
		"PATH":                      true,
		"PCTFREE":                   true,
		"PCTINCREASE":               true,
		"PCTTHRESHOLD":              true,
		"PCTUSED":                   true,
		"PCTVERSION":                true,
		"PERFORMANCE":               true,
		"PERMANENT":                 true,
		"PFILE":                     true,
		"PHYSICAL":                  true,
		"PIV_GB":                    true,
		"PIV_SSF":                   true,
		"PLAN":                      true,
		"PLSQL_CCFLAGS":             true,
		"PLSQL_CODE_TYPE":           true,
		"PLSQL_DEBUG":               true,
		"PLSQL_OPTIMIZE_LEVEL":      true,
		"PLSQL_WARNINGS":            true,
		"POLICY":                    true,
		"POST_TRANSACTION":          true,
		"POWER":                     true,
		"PRAGMA":                    true,
		"PREBUILT":                  true,
		"PRECEDING":                 true,
		"PRESERVE":                  true,
		"PRESERVE_OID":              true,
		"PRIOR":                     true,
		"PRIVATE":                   true,
		"PRIVATE_SGA":               true,
		"PRIVILEGE":                 true,
		"PRIVILEGES":                true,
		"PROFILE":                   true,
		"PROGRAM":                   true,
		"PROJECT":                   true,
		"PROTECTED":                 true,
		"PROTECTION":                true,
		"PUBLIC":                    true,
		"PURGE":                     true,
		"QUERY":                     true,
		"QUIESCE":                   true,
		"QUOTA":                     true,
		"RANDOM":                    true,
		"RANGE":                     true,
		"RAW":                       true,
		"READ":                      true,
		"READS":                     true,
		"REBUILD":                   true,
		"RECORDS_PER_BLOCK":         true,
		"RECOVER":                   true,
		"RECOVERY":                  true,
		"RECYCLEBIN":                true,
		"REDUCED":                   true,
		"REDUNDANCY":                true,
		"REF":                       true,
		"REFERENCE":                 true,
		"REFERENCED":                true,
		"REFERENCING":               true,
		"REFRESH":                   true,
		"REGISTER":                  true,
		"REGISTERED":                true,
		"REJECT":                    true,
		"RELY":                      true,
		"REMOTE_DEPENDENCIES_MODE":  true,
		"RENAME":                    true,
		"REPAIR":                    true,
		"REPLACE":                   true,
		"REQUIRED":                  true,
		"RESET":                     true,
		"RESETLOGS":                 true,
		"RESIZE":                    true,
		"RESOLVE":                   true,
		"RESOLVER":                  true,
		"RESTRICT":                  true,
		"RESTRICTED":                true,
		"RESUMABLE":                 true,
		"RESUME":                    true,
		"RETENTION":                 true,
		"RETURN":                    true,
		"RETURNING":                 true,
		"REUSE":                     true,
		"REVERSE":                   true,
		"REWRITE":                   true,
		"ROLES":                     true,
		"ROLLBACK":                  true,
		"ROLLUP":                    true,
		"ROW":                       true,
		"ROWDEPENDENCIES":           true,
		"ROWID":                     true,
		"ROWNUM":                    true,
		"ROWS":                      true,
		"RULE":                      true,
		"SAMPLE":                    true,
		"SAVEPOINT":                 true,
		"SCAN":                      true,
		"SCAN_INSTANCES":            true,
		"SCHEDULER":                 true,
		"SCN":                       true,
		"SCOPE":                     true,
		"SECOND":                    true,
		"SECURITY":                  true,
		"SEGMENT":                   true,
		"SELF":                      true,
		"SERIALIZABLE":              true,
		"SESSION":                   true,
		"SESSIONS_PER_USER":         true,
		"SHARE":                     true,
		"SHARED":                    true,
		"SHARED_POOL":               true,
		"SHRINK":                    true,
		"SHUTDOWN":                  true,
		"SIBLINGS":                  true,
		"SINGLE":                    true,
		"SIZE":                      true,
		"SKIP":                      true,
		"SORT":                      true,
		"SOURCE":                    true,
		"SPACE":                     true,
		"SPECIFICATION":             true,
		"SPFILE":                    true,
		"SPLIT":                     true,
		"STANDBY":                   true,
		"START":                     true,
		"STATEMENT_ID":              true,
		"STATIC":                    true,
		"STATISTICS":                true,
		"STOP":                      true,
		"STORAGE":                   true,
		"STORE":                     true,
		"STRUCTURE":                 true,
		"SUBMULTISET":               true,
		"SUBPARTITION":              true,
		"SUBPARTITIONS":             true,
		"SUBSTITUTABLE":             true,
		"SUBTYPE":                   true,
		"SUCCESS":                   true,
		"SUSPEND":                   true,
		"SWITCH":                    true,
		"SWITCHOVER":                true,
		"SYS_OP_BITVEC":             true,
		"SYS_OP_ENFORCE_NOT_NULL$":  true,
		"SYS_OP_NTCIMG$":            true,
		"SYNONYM":                   true,
		"SYSDATE":                   true,
		"SYSDBA":                    true,
		"SYSOPER":                   true,
		"SYSTEM":                    true,
		"TABLES":                    true,
		"TABLESPACE":                true,
		"TEMPFILE":                  true,
		"TEMPORARY":                 true,
		"TEMPORARY_TABLESPACE":      true,
		"TERMINATE":                 true,
		"THREAD":                    true,
		"THROUGH":                   true,
		"TIES":                      true,
		"TIME":                      true,
		"TIMEOUT":                   true,
		"TIMEZONE_ABBR":             true,
		"TIMEZONE_HOUR":             true,
		"TIMEZONE_MINUTE":           true,
		"TIMEZONE_REGION":           true,
		"TRACE":                     true,
		"TRANSACTION":               true,
		"TRANSITIONAL":              true,
		"TRIGGERS":                  true,
		"TRUNCATE":                  true,
		"TRUSTED":                   true,
		"TUNING":                    true,
		"TX":                        true,
		"TYPE":                      true,
		"TYPES":                     true,
		"UID":                       true,
		"UNARCHIVED":                true,
		"UNBOUNDED":                 true,
		"UNDEFINE":                  true,
		"UNDER":                     true,
		"UNDO":                      true,
		"UNDROP":                    true,
		"UNIFORM":                   true,
		"UNLIMITED":                 true,
		"UNLOCK":                    true,
		"UNPACKED":                  true,
		"UNPROTECTED":               true,
		"UNQUIESCE":                 true,
		"UNRECOVERABLE":             true,
		"UNTIL":                     true,
		"UNUSABLE":                  true,
		"UNUSED":                    true,
		"UPDATABLE":                 true,
		"UPGRADE":                   true,
		"USAGE":                     true,
		"USE":                       true,
		"VALIDATE":                  true,
		"VALIDATION":                true,
		"VALUE":                     true,
		"VARRAY":                    true,
		"VERIFY":                    true,
		"VIRTUAL":                   true,
		"VISIBLE":                   true,
		"WAIT":                      true,
		"WALLET":                    true,
		"WELLFORMED":                true,
		"WORK":                      true,
		"WRAPPED":                   true,
		"WRITE":                     true,
		"XMLATTRIBUTES":             true,
		"XMLCOLATTVAL":              true,
		"XMLELEMENT":                true,
		"XMLFOREST":                 true,
		"XMLPARSE":                  true,
		"XMLROOT":                   true,
		"XMLSCHEMA":                 true,
		"XMLSERIALIZE":              true,
		"XMLTABLE":                  true,
		"XMLTYPE":                   true,
		"YEAR":                      true,
		"YES":                       true,
		"ZONE":                      true,
	}
)
