package db

var (
	postgresKeywords = map[string]bool{
		// PostgreSQL specific reserved words (that aren't in the common list)
		"ABORT": true, "ABSOLUTE": true, "ACCESS": true, "ADMIN": true,
		"AGGREGATE": true, "ALSO": true, "ANALYSE": true, "ANALYZE": true,
		"ASSERTION": true, "ASSIGNMENT": true, "ASYMMETRIC": true, "AT": true,
		"ATOMIC": true, "AUTHORIZATION": true, "BACKWARD": true, "BEFORE": true,
		"BINARY": true, "CACHE": true, "CALLED": true, "CASCADE": true,
		"CATALOG": true, "CHAIN": true, "CHARACTERISTICS": true, "CHECKPOINT": true,
		"CLASS": true, "CLUSTER": true, "COLLATION": true, "COLLATE": true,
		"COLUMN": true, "COMMENT": true, "COMMENTS": true, "COMMIT": true,
		"COMMITTED": true, "CONCURRENTLY": true, "CONFIGURATION": true, "CONNECTION": true,
		"CONSTRAINTS": true, "CONTENT": true, "CONTINUE": true, "CONVERSION": true,
		"COPY": true, "COST": true, "CREATEDB": true, "CREATEROLE": true,
		"CREATEUSER": true, "CSV": true, "CURRENT": true, "CURRENT_CATALOG": true,
		"CURRENT_ROLE": true, "CURRENT_SCHEMA": true, "CYCLE": true, "DATA": true,
		"DATABASE": true, "DAY": true, "DEALLOCATE": true, "DECLARE": true,
		"DEFAULTS": true, "DEFERRED": true, "DEFINER": true, "DELIMITER": true,
		"DELIMITERS": true, "DICTIONARY": true, "DISABLE": true, "DISCARD": true,
		"DOCUMENT": true, "DOMAIN": true, "EACH": true, "ENABLE": true,
		"ENCODING": true, "ENCRYPTED": true, "ENUM": true, "ESCAPE": true,
		"EVENT": true, "EXCLUDE": true, "EXCLUDING": true, "EXCLUSIVE": true,
		"EXECUTE": true, "EXPLAIN": true, "EXTENSION": true, "EXTERNAL": true,
		"FAMILY": true, "FILTER": true, "FIRST": true, "FOLLOWING": true,
		"FORCE": true, "FORWARD": true, "FREEZE": true, "FUNCTIONS": true,
		"GENERATED": true, "GLOBAL": true, "GRANTED": true, "HANDLER": true,
		"HEADER": true, "HOLD": true, "HOUR": true, "IDENTITY": true,
		"IF": true, "ILIKE": true, "IMMEDIATE": true, "IMMUTABLE": true,
		"IMPLICIT": true, "INCLUDING": true, "INCREMENT": true, "INDEX": true,
		"INDEXES": true, "INHERIT": true, "INHERITS": true, "INLINE": true,
		"INPUT": true, "INSENSITIVE": true, "INSTEAD": true,
		"INVOKER": true, "ISOLATION": true, "KEY": true, "LABEL": true,
		"LANGUAGE": true, "LARGE": true, "LAST": true, "LATERAL": true,
		"LEAKPROOF": true, "LEVEL": true, "LISTEN": true, "LOAD": true,
		"LOCAL": true, "LOCATION": true, "LOCK": true, "LOGGED": true,
		"MAPPING": true, "MATCH": true, "MATERIALIZED": true, "MAXVALUE": true,
		"METHOD": true, "MINUTE": true, "MINVALUE": true, "MODE": true,
		"MONTH": true, "MOVE": true, "NAME": true, "NAMES": true,
		"NEXT": true, "NO": true, "NOTHING": true, "NOTIFY": true,
		"NOWAIT": true, "NULLS": true, "OBJECT": true, "OF": true,
		"OFF": true, "OIDS": true, "OPERATOR": true, "OPTION": true,
		"OPTIONS": true, "OWNED": true, "OWNER": true, "PARALLEL": true,
		"PARSER": true, "PARTIAL": true, "PARTITION": true, "PASSING": true,
		"PASSWORD": true, "PLACING": true, "PLANS": true, "POLICY": true,
		"PORTION": true, "PRECEDING": true, "PREPARE": true, "PREPARED": true,
		"PRESERVE": true, "PRIOR": true, "PRIVILEGES": true, "PROCEDURAL": true,
		"PROCEDURE": true, "PROGRAM": true, "PUBLICATION": true, "QUOTE": true,
		"RANGE": true, "READ": true, "REASSIGN": true, "RECHECK": true,
		"RECURSIVE": true, "REF": true, "REFERENCING": true, "REFRESH": true,
		"REINDEX": true, "RELATIVE": true, "RELEASE": true, "RENAME": true,
		"REPEATABLE": true, "REPLACE": true, "REPLICA": true, "RESET": true,
		"RESTART": true, "RESTRICT": true, "RETURNING": true, "RETURNS": true,
		"REVOKE": true, "ROLE": true, "ROLLBACK": true, "ROWS": true,
		"RULE": true, "SAVEPOINT": true, "SCHEMA": true, "SCHEMAS": true,
		"SCROLL": true, "SEARCH": true, "SECOND": true, "SECURITY": true,
		"SEQUENCE": true, "SEQUENCES": true, "SERIALIZABLE": true, "SERVER": true,
		"SESSION": true, "SET": true, "SHARE": true, "SHOW": true,
		"SIMILAR": true, "SIMPLE": true, "SKIP": true, "SNAPSHOT": true,
		"SQL": true, "STABLE": true, "STANDALONE": true, "START": true,
		"STATEMENT": true, "STATISTICS": true, "STDIN": true, "STDOUT": true,
		"STORAGE": true, "STORED": true, "STRICT": true, "STRIP": true,
		"SUBSCRIPTION": true, "SUPPORT": true, "SYSID": true, "SYSTEM": true,
		"TABLES": true, "TABLESPACE": true, "TEMP": true, "TEMPLATE": true,
		"TEMPORARY": true, "TEXT": true, "TIES": true, "TRANSACTION": true,
		"TRANSFORM": true, "TRIGGER": true, "TRUNCATE": true, "TRUSTED": true,
		"TYPE": true, "TYPES": true, "UNBOUNDED": true, "UNCOMMITTED": true,
		"UNENCRYPTED": true, "UNKNOWN": true, "UNLISTEN": true, "UNLOGGED": true,
		"UNTIL": true, "VACUUM": true, "VALID": true, "VALIDATE": true,
		"VALIDATOR": true, "VALUE": true, "VARYING": true, "VERSION": true,
		"VIEW": true, "VOLATILE": true, "WHITESPACE": true, "WITHIN": true,
		"WITHOUT": true, "WORK": true, "WRAPPER": true, "WRITE": true,
		"XML": true, "YEAR": true, "YES": true, "ZONE": true,
	}

	// postgresKeywordsCanBeUsedAsFieldNameDirectly contains PostgreSQL keywords that are
	// non-reserved and can be used as column/table names without double quotes.
	// Based on PostgreSQL official documentation (version 17.6)
	postgresKeywordsCanBeUsedAsFieldNameDirectly = map[string]bool{
		// Non-reserved PostgreSQL keywords - safe to use as identifiers
		"ABORT":           true,
		"ABSOLUTE":        true,
		"ACCESS":          true,
		"ADMIN":           true,
		"AGGREGATE":       true,
		"ALSO":            true,
		"ASSERTION":       true,
		"ASSIGNMENT":      true,
		"AT":              true,
		"BACKWARD":        true,
		"BEFORE":          true,
		"CACHE":           true,
		"CALLED":          true,
		"CASCADE":         true,
		"CATALOG":         true,
		"CHAIN":           true,
		"CHARACTERISTICS": true,
		"CHECKPOINT":      true,
		"CLASS":           true,
		"CLUSTER":         true,
		"COMMENT":         true,
		"COMMENTS":        true,
		"COMMIT":          true,
		"COMMITTED":       true,
		"CONFIGURATION":   true,
		"CONNECTION":      true,
		"CONSTRAINTS":     true,
		"CONTENT":         true,
		"CONTINUE":        true,
		"CONVERSION":      true,
		"COPY":            true,
		"COST":            true,
		"CREATEDB":        true,
		"CREATEROLE":      true,
		"CREATEUSER":      true,
		"CSV":             true,
		"CURRENT":         true,
		"CYCLE":           true,
		"DATA":            true,
		"DATABASE":        true,
		"DAY":             true,
		"DEALLOCATE":      true,
		"DECLARE":         true,
		"DEFAULTS":        true,
		"DEFERRED":        true,
		"DEFINER":         true,
		"DELIMITER":       true,
		"DELIMITERS":      true,
		"DICTIONARY":      true,
		"DISABLE":         true,
		"DISCARD":         true,
		"DOCUMENT":        true,
		"DOMAIN":          true,
		"EACH":            true,
		"ENABLE":          true,
		"ENCODING":        true,
		"ENCRYPTED":       true,
		"ENUM":            true,
		"ESCAPE":          true,
		"EVENT":           true,
		"EXCLUDE":         true,
		"EXCLUDING":       true,
		"EXCLUSIVE":       true,
		"EXECUTE":         true,
		"EXPLAIN":         true,
		"EXTENSION":       true,
		"EXTERNAL":        true,
		"FAMILY":          true,
		"FILTER":          true,
		"FIRST":           true,
		"FOLLOWING":       true,
		"FORCE":           true,
		"FORWARD":         true,
		"FREEZE":          true,
		"FUNCTIONS":       true,
		"GENERATED":       true,
		"GLOBAL":          true,
		"GRANTED":         true,
		"HANDLER":         true,
		"HEADER":          true,
		"HOLD":            true,
		"HOUR":            true,
		"IDENTITY":        true,
		"IF":              true,
		"IMMEDIATE":       true,
		"IMMUTABLE":       true,
		"IMPLICIT":        true,
		"INCLUDING":       true,
		"INCREMENT":       true,
		"INDEX":           true,
		"INDEXES":         true,
		"INHERIT":         true,
		"INHERITS":        true,
		"INLINE":          true,
		"INPUT":           true,
		"INSENSITIVE":     true,
		"INSTEAD":         true,
		"INVOKER":         true,
		"ISOLATION":       true,
		"KEY":             true,
		"LABEL":           true,
		"LANGUAGE":        true,
		"LARGE":           true,
		"LAST":            true,
		"LEAKPROOF":       true,
		"LEVEL":           true,
		"LISTEN":          true,
		"LOAD":            true,
		"LOCAL":           true,
		"LOCATION":        true,
		"LOCK":            true,
		"LOGGED":          true,
		"MAPPING":         true,
		"MATCH":           true,
		"MATERIALIZED":    true,
		"MAXVALUE":        true,
		"METHOD":          true,
		"MINUTE":          true,
		"MINVALUE":        true,
		"MODE":            true,
		"MONTH":           true,
		"MOVE":            true,
		"NAME":            true,
		"NAMES":           true,
		"NEXT":            true,
		"NO":              true,
		"NOTHING":         true,
		"NOTIFY":          true,
		"NOWAIT":          true,
		"NULLS":           true,
		"OBJECT":          true,
		"OF":              true,
		"OFF":             true,
		"OIDS":            true,
		"OPERATOR":        true,
		"OPTION":          true,
		"OPTIONS":         true,
		"OWNED":           true,
		"OWNER":           true,
		"PARALLEL":        true,
		"PARSER":          true,
		"PARTIAL":         true,
		"PARTITION":       true,
		"PASSING":         true,
		"PASSWORD":        true,
		"PLACING":         true,
		"PLANS":           true,
		"POLICY":          true,
		"PORTION":         true,
		"PRECEDING":       true,
		"PREPARE":         true,
		"PREPARED":        true,
		"PRESERVE":        true,
		"PRIOR":           true,
		"PRIVILEGES":      true,
		"PROCEDURAL":      true,
		"PROCEDURE":       true,
		"PROGRAM":         true,
		"PUBLICATION":     true,
		"QUOTE":           true,
		"RANGE":           true,
		"READ":            true,
		"REASSIGN":        true,
		"RECHECK":         true,
		"RECURSIVE":       true,
		"REF":             true,
		"REFERENCING":     true,
		"REFRESH":         true,
		"REINDEX":         true,
		"RELATIVE":        true,
		"RELEASE":         true,
		"RENAME":          true,
		"REPEATABLE":      true,
		"REPLACE":         true,
		"REPLICA":         true,
		"RESET":           true,
		"RESTART":         true,
		"RESTRICT":        true,
		"RETURNING":       true,
		"RETURNS":         true,
		"REVOKE":          true,
		"ROLE":            true,
		"ROLLBACK":        true,
		"ROWS":            true,
		"RULE":            true,
		"SAVEPOINT":       true,
		"SCHEMA":          true,
		"SCHEMAS":         true,
		"SCROLL":          true,
		"SEARCH":          true,
		"SECOND":          true,
		"SECURITY":        true,
		"SEQUENCE":        true,
		"SEQUENCES":       true,
		"SERIALIZABLE":    true,
		"SERVER":          true,
		"SESSION":         true,
		"SET":             true,
		"SHARE":           true,
		"SHOW":            true,
		"SIMPLE":          true,
		"SKIP":            true,
		"SNAPSHOT":        true,
		"SQL":             true,
		"STABLE":          true,
		"STANDALONE":      true,
		"START":           true,
		"STATEMENT":       true,
		"STATISTICS":      true,
		"STDIN":           true,
		"STDOUT":          true,
		"STORAGE":         true,
		"STORED":          true,
		"STRICT":          true,
		"STRIP":           true,
		"SUBSCRIPTION":    true,
		"SUPPORT":         true,
		"SYSID":           true,
		"SYSTEM":          true,
		"TABLES":          true,
		"TABLESPACE":      true,
		"TEMP":            true,
		"TEMPLATE":        true,
		"TEMPORARY":       true,
		"TEXT":            true,
		"TIES":            true,
		"TRANSACTION":     true,
		"TRANSFORM":       true,
		"TRIGGER":         true,
		"TRUNCATE":        true,
		"TRUSTED":         true,
		"TYPE":            true,
		"TYPES":           true,
		"UNBOUNDED":       true,
		"UNCOMMITTED":     true,
		"UNENCRYPTED":     true,
		"UNKNOWN":         true,
		"UNLISTEN":        true,
		"UNLOGGED":        true,
		"UNTIL":           true,
		"VACUUM":          true,
		"VALID":           true,
		"VALIDATE":        true,
		"VALIDATOR":       true,
		"VALUE":           true,
		"VERSION":         true,
		"VIEW":            true,
		"VOLATILE":        true,
		"WHITESPACE":      true,
		"WORK":            true,
		"WRAPPER":         true,
		"WRITE":           true,
		"YEAR":            true,
		"YES":             true,
		"ZONE":            true,
	}
)
