package db

var (
	// SQL Server-specific keywords
	sqlServerKeywords = map[string]bool{
		// SQL Server specific reserved keywords (that aren't in the common list)
		"ABSOLUTE": true, "ACTION": true, "ADMIN": true, "AFTER": true,
		"AGGREGATE": true, "ALGORITHM": true, "ALLOW_SNAPSHOT_ISOLATION": true, "ANSI_NULLS": true,
		"ANSI_PADDING": true, "ANSI_WARNINGS": true, "APPLICATION_LOG": true, "APPLY": true,
		"ASSEMBLY": true, "ASYMMETRIC": true, "ATOMIC": true, "AUDIT": true,
		"AUTHORIZATION": true, "AUTO": true, "AUTO_CLEANUP": true, "AUTO_CLOSE": true,
		"AUTO_CREATE_STATISTICS": true, "AUTO_SHRINK": true, "AUTO_UPDATE_STATISTICS": true, "AVAILABILITY": true,
		"BACKUP": true, "BEFORE": true, "BEGIN": true, "BINARY": true,
		"BINDING": true, "BLOB_STORAGE": true, "BROKER": true, "BROKER_INSTANCE": true,
		"BULK": true, "CALLER": true, "CAP_CPU_PERCENT": true, "CASCADE": true,
		"CATALOG": true, "CATCH": true, "CHANGE_RETENTION": true, "CHANGE_TRACKING": true,
		"CHECKSUM": true, "CLASSIFIER_FUNCTION": true, "CLEANUP": true, "COLLECTION": true,
		"COLUMNSTORE": true, "COMMITTED": true, "COMPATIBILITY_LEVEL": true, "COMPRESS_ALL_ROW_GROUPS": true,
		"COMPRESSION": true, "CONCAT": true, "CONCAT_NULL_YIELDS_NULL": true, "CONTROL": true,
		"COOKIE": true, "CROSS": true, "CURSOR_CLOSE_ON_COMMIT": true, "CURSOR_DEFAULT": true,
		"DATA": true, "DATA_COMPRESSION": true, "DATA_PURITY": true, "DATABASE": true,
		"DATABASE_MIRRORING": true, "DATE_CORRELATION_OPTIMIZATION": true, "DATEADD": true, "DATEDIFF": true,
		"DATENAME": true, "DATEPART": true, "DAYS": true, "DB_CHAINING": true,
		"DBCC": true, "DEALLOCATE": true, "DECLARE": true, "DEFAULT_DATABASE": true,
		"DEFAULT_FULLTEXT_LANGUAGE": true, "DEFAULT_LANGUAGE": true, "DEFAULT_SCHEMA": true, "DELAYED_DURABILITY": true,
		"DENY": true, "DENSE_RANK": true, "DIRECTORY_NAME": true, "DISABLE": true,
		"DISABLED": true, "DISABLE_BROKER": true, "DISK": true, "DISTRIBUTED": true,
		"DUMP": true, "DURABILITY": true, "ELEMENTS": true, "EMERGENCY": true,
		"ENABLE": true, "ENABLE_BROKER": true, "ENCRYPTED": true, "ENCRYPTION": true,
		"ENDPOINT": true, "ERRLVL": true, "ERROR_BROKER_CONVERSATIONS": true, "ESCAPE": true,
		"EVENT": true, "EVENTDATA": true, "EXCLUSIVE": true, "EXECUTABLE": true,
		"EXECUTE": true, "EXIT": true, "EXPANDABLE": true, "FAST": true,
		"FAST_FORWARD": true, "FETCH": true, "FILE": true, "FILEGROUP": true,
		"FILEGROWTH": true, "FILENAME": true, "FILESTREAM": true, "FILLFACTOR": true,
		"FILTER": true, "FIRST": true, "FOLLOWING": true, "FOR": true,
		"FORCE": true, "FORCED": true, "FORCESEEK": true, "FOREIGN": true,
		"FORWARD_ONLY": true, "FREE": true, "FULLSCAN": true, "FULLTEXT": true,
		"GB": true, "GETDATE": true, "GETUTCDATE": true, "GO": true,
		"GOVERNOR": true, "GROUP_MAX_REQUESTS": true, "HADR": true, "HASH": true,
		"HASHED": true, "HEALTHCHECKTIMEOUT": true, "HONOR_BROKER_PRIORITY": true, "HOURS": true,
		"IDENTITY_INSERT": true, "IGNORE_CONSTRAINTS": true, "IGNORE_DUP_KEY": true, "IGNORE_NONCLUSTERED_COLUMNSTORE_INDEX": true,
		"IGNORE_TRIGGERS": true, "IMMEDIATE": true, "IMPERSONATE": true, "INCLUDE": true,
		"INCREMENT": true, "INCREMENTAL": true, "INFINITE": true, "INIT": true,
		"INSENSITIVE": true, "INSERTED": true, "ISOLATION": true, "KB": true,
		"KEEP": true, "KEEPDEFAULTS": true, "KEEPFIXED": true, "KEEPIDENTITY": true,
		"KEY": true, "KEYSET": true, "LANGUAGE": true, "LAST": true,
		"LEVEL": true, "LIBRARY": true, "LIFETIME": true, "LINKED": true,
		"LINUX": true, "LISTENER": true, "LISTENER_URL": true, "LOB_COMPACTION": true,
		"LOCAL": true, "LOCAL_SERVICE_NAME": true, "LOCK": true, "LOCK_ESCALATION": true,
		"LOG": true, "LOGIN": true, "LOOP": true, "MANUAL": true,
		"MARK": true, "MASTER": true, "MAX": true, "MAX_CPU_PERCENT": true,
		"MAX_DOP": true, "MAX_FILES": true, "MAX_MEMORY": true, "MAX_MEMORY_PERCENT": true,
		"MAX_PROCESSES": true, "MAX_QUEUE_READERS": true, "MAX_ROLLOVER_FILES": true, "MAXDOP": true,
		"MAXRECURSION": true, "MAXSIZE": true, "MB": true, "MEDIUM": true,
		"MEMORY_OPTIMIZED": true, "MERGE": true, "MESSAGE": true, "MIN": true,
		"MIN_ACTIVE_ROWVERSION": true, "MIN_CPU_PERCENT": true, "MIN_MEMORY_PERCENT": true, "MINUTES": true,
		"MIRROR": true, "MIRROR_ADDRESS": true, "MIXED_PAGE_ALLOCATION": true, "MODE": true,
		"MODIFY": true, "MOVE": true, "MULTI_USER": true, "NAME": true,
		"NATIVE_COMPILATION": true, "NESTED_TRIGGERS": true, "NEW_BROKER": true, "NEWNAME": true,
		"NEXT": true, "NO": true, "NO_CHECKSUM": true, "NO_COMPRESSION": true,
		"NO_EVENT_LOSS": true, "NO_TRUNCATE": true, "NO_WAIT": true, "NOCOUNT": true,
		"NODES": true, "NOEXPAND": true, "NON_TRANSACTED_ACCESS": true, "NORECOMPUTE": true,
		"NORECOVERY": true, "NOWAIT": true, "NTILE": true, "NUMANODE": true,
		"NUMERIC_ROUNDABORT": true, "OBJECT": true, "OFFLINE": true, "OFFSET": true,
		"OLD_PASSWORD": true, "ONLINE": true, "ONLY": true, "OPEN": true,
		"OPEN_EXISTING": true, "OPENQUERY": true, "OPENROWSET": true, "OPENXML": true,
		"OPTIMISTIC": true, "OPTIMIZE": true, "OPTIMIZE_FOR_SEQUENTIAL_KEY": true, "OPTION": true,
		"OUT": true, "OUTPUT": true, "OWNER": true, "OWNERSHIP": true,
		"PAGE": true, "PAGECOUNT": true, "PARTITION": true, "PARTITIONS": true,
		"PASSWORD": true, "PATH": true, "PERCENT": true, "PERCENT_RANK": true,
		"PERCENTILE_CONT": true, "PERCENTILE_DISC": true, "PERMISSION_SET": true, "PERSISTED": true,
		"PILOT": true, "PIVOT": true, "PLAN": true, "POLICY": true,
		"POOL": true, "POPULATION": true, "PRECEDING": true, "PRECISION": true,
		"PREDICATE": true, "PRIMARY_ROLE": true, "PRIOR": true, "PRIORITY": true,
		"PRIORITY_LEVEL": true, "PRIVATE": true, "PRIVILEGES": true, "PROCEDURE": true,
		"PROCESS": true, "PROFILE": true, "PROPERTY": true, "PROVIDER": true,
		"QUERY_STORE": true, "QUEUE": true, "QUOTED_IDENTIFIER": true, "RAISERROR": true,
		"RANGE": true, "RANK": true, "RC2": true, "RC4": true,
		"RC4_128": true, "READ_COMMITTED_SNAPSHOT": true, "READ_ONLY": true, "READ_WRITE": true,
		"READCOMMITTED": true, "READCOMMITTEDLOCK": true, "READONLY": true, "READPAST": true,
		"READUNCOMMITTED": true, "READWRITE": true, "REBUILD": true, "RECEIVE": true,
		"RECOMPILE": true, "RECOVERY": true, "RECURSIVE": true, "RECURSIVE_TRIGGERS": true,
		"REFERENCES": true, "REGENERATE": true, "RELATED_CONVERSATION": true, "RELATED_CONVERSATION_GROUP": true,
		"RELATIVE": true, "REMOTE": true, "REMOTE_PROC_TRANSACTIONS": true, "REMOTE_SERVICE_NAME": true,
		"REMOVE": true, "REORGANIZE": true, "REPEATABLE": true, "REPEATABLEREAD": true,
		"REPLACE": true, "REPLICA": true, "REPLICATE": true, "REQUEST_MAX_CPU_TIME_SEC": true,
		"REQUEST_MAX_MEMORY_GRANT_PERCENT": true, "REQUEST_MEMORY_GRANT_TIMEOUT_SEC": true, "REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT": true, "RESAMPLE": true,
		"RESET": true, "RESTART": true, "RESTORE": true, "RESTRICT_GEOM_SPEC_TO_REGIONATOR": true,
		"RESTRICTED_USER": true, "RESUMABLE": true, "RETENTION": true, "RETURN": true,
		"RETURNS": true, "REVERT": true, "ROLE": true, "ROLLBACK": true,
		"ROUTE": true, "ROW": true, "ROW_NUMBER": true, "ROWCOUNT": true,
		"ROWGUID": true, "ROWGUIDCOL": true, "ROWS": true, "ROWS_PER_BATCH": true,
		"RSA_1024": true, "RSA_2048": true, "RSA_3072": true, "RSA_4096": true,
		"RSA_512": true, "SAFETY": true, "SAFE": true, "SAMPLE": true,
		"SAVE": true, "SCHEDULER": true, "SCHEMA": true, "SCHEMA_ID": true,
		"SCHEMA_NAME": true, "SCHEMABINDING": true, "SCOPE": true, "SCROLL": true,
		"SCROLL_LOCKS": true, "SEARCH": true, "SECONDS": true, "SECONDARY": true,
		"SECONDARY_ONLY": true, "SECONDARY_ROLE": true, "SECURITY": true, "SECURITY_LOG": true,
		"SECURITYAUDIT": true, "SELECTIVE": true, "SELF": true, "SEND": true,
		"SENT": true, "SEQUENCE": true, "SERIALIZABLE": true, "SERVER": true,
		"SERVICE": true, "SERVICE_BROKER": true, "SERVICE_NAME": true, "SESSION": true,
		"SESSION_TIMEOUT": true, "SETERROR": true, "SETS": true, "SETTINGS": true,
		"SHOWPLAN": true, "SHOWPLAN_ALL": true, "SHOWPLAN_TEXT": true, "SHOWPLAN_XML": true,
		"SHRINKLOG": true, "SHUTDOWN": true, "SID": true, "SIGNATURE": true,
		"SIMPLE": true, "SINGLE_USER": true, "SIZE": true, "SMALLINT": true,
		"SNAPSHOT": true, "SORT_IN_TEMPDB": true, "SOURCE": true, "SPARSE": true,
		"SPATIAL": true, "SPECIFICATION": true, "SPLIT": true, "SQL": true,
		"SQLDUMPERFLAGS": true, "SQLDUMPERUSERDUMPS": true, "SQLDUMPERSETUPFLAGS": true, "STANDBY": true,
		"START": true, "START_DATE": true, "STARTED": true, "STARTUP_STATE": true,
		"STATE": true, "STATIC": true, "STATISTICAL_SEMANTICS": true, "STATISTICS": true,
		"STATISTICS_INCREMENTAL": true, "STATISTICS_NORECOMPUTE": true, "STATS": true, "STATS_STREAM": true,
		"STATUS": true, "STATUSONLY": true, "STOP": true, "STOPLIST": true,
		"STOPPED": true, "STRING_AGG": true, "SUBJECT": true, "SUBSCRIPTION": true,
		"SUPPORTED": true, "SUSPEND": true, "SWITCH": true, "SYMMETRIC": true,
		"SYNCHRONOUS_COMMIT": true, "SYNONYM": true, "SYSTEM": true, "TAKE": true,
		"TARGET": true, "TARGET_RECOVERY_TIME": true, "TB": true, "TEXTSIZE": true,
		"THROW": true, "TIES": true, "TIME": true, "TIMEOUT": true,
		"TIMER": true, "TINYINT": true, "TOP": true, "TORN_PAGE_DETECTION": true,
		"TRACK_CAUSALITY": true, "TRANSFER": true, "TRANSFORM_NOISE_WORDS": true, "TRIGGER": true,
		"TRIPLE_DES": true, "TRIPLE_DES_3KEY": true, "TRUSTWORTHY": true, "TRY": true,
		"TSQL": true, "TWO_DIGIT_YEAR_CUTOFF": true, "TYPE": true, "TYPE_WARNING": true,
		"UNBOUNDED": true, "UNCOMMITTED": true, "UNCHECKED": true, "UNDEFINED": true,
		"UNLIMITED": true, "UNMASK": true, "UNPIVOT": true, "UNSAFE": true,
		"URL": true, "USAGE": true, "USE": true, "USED": true,
		"USER": true, "USER_OPTIONS": true, "USING": true, "VALIDATION": true,
		"VALUE": true, "VARYING": true, "VIEW": true, "VIEWS": true,
		"WAIT": true, "WAITFOR": true, "WELL_FORMED_XML": true, "WINDOWS": true,
		"WITHOUT": true, "WITNESS": true, "WORK": true, "WORKLOAD": true,
		"XML": true, "XMLNAMESPACES": true, "XSINIL": true, "ZONE": true,
	}

	// sqlServerKeywordsCanBeUsedAsFieldNameDirectly contains SQL Server keywords that are
	// non-reserved and can be used as column/table names without brackets.
	// Based on SQL Server T-SQL official documentation
	sqlServerKeywordsCanBeUsedAsFieldNameDirectly = map[string]bool{
		// Non-reserved SQL Server keywords - safe to use as identifiers
		"ABSOLUTE":                              true,
		"ACTION":                                true,
		"ADMIN":                                 true,
		"AFTER":                                 true,
		"AGGREGATE":                             true,
		"ALGORITHM":                             true,
		"ALLOW_SNAPSHOT_ISOLATION":              true,
		"ANSI_NULLS":                            true,
		"ANSI_PADDING":                          true,
		"ANSI_WARNINGS":                         true,
		"APPLICATION_LOG":                       true,
		"APPLY":                                 true,
		"ASSEMBLY":                              true,
		"ASYMMETRIC":                            true,
		"ATOMIC":                                true,
		"AUDIT":                                 true,
		"AUTO":                                  true,
		"AUTO_CLEANUP":                          true,
		"AUTO_CLOSE":                            true,
		"AUTO_CREATE_STATISTICS":                true,
		"AUTO_SHRINK":                           true,
		"AUTO_UPDATE_STATISTICS":                true,
		"AVAILABILITY":                          true,
		"BACKUP":                                true,
		"BEFORE":                                true,
		"BEGIN":                                 true,
		"BINDING":                               true,
		"BLOB_STORAGE":                          true,
		"BROKER":                                true,
		"BROKER_INSTANCE":                       true,
		"BULK":                                  true,
		"CALLER":                                true,
		"CAP_CPU_PERCENT":                       true,
		"CATALOG":                               true,
		"CATCH":                                 true,
		"CHANGE_RETENTION":                      true,
		"CHANGE_TRACKING":                       true,
		"CHECKSUM":                              true,
		"CLASSIFIER_FUNCTION":                   true,
		"CLEANUP":                               true,
		"COLLECTION":                            true,
		"COLUMNSTORE":                           true,
		"COMMITTED":                             true,
		"COMPATIBILITY_LEVEL":                   true,
		"COMPRESS_ALL_ROW_GROUPS":               true,
		"COMPRESSION":                           true,
		"CONCAT":                                true,
		"CONCAT_NULL_YIELDS_NULL":               true,
		"CONTROL":                               true,
		"COOKIE":                                true,
		"CURSOR_CLOSE_ON_COMMIT":                true,
		"CURSOR_DEFAULT":                        true,
		"DATA":                                  true,
		"DATA_COMPRESSION":                      true,
		"DATA_PURITY":                           true,
		"DATABASE_MIRRORING":                    true,
		"DATE_CORRELATION_OPTIMIZATION":         true,
		"DATEADD":                               true,
		"DATEDIFF":                              true,
		"DATENAME":                              true,
		"DATEPART":                              true,
		"DAYS":                                  true,
		"DB_CHAINING":                           true,
		"DBCC":                                  true,
		"DEALLOCATE":                            true,
		"DECLARE":                               true,
		"DEFAULT_DATABASE":                      true,
		"DEFAULT_FULLTEXT_LANGUAGE":             true,
		"DEFAULT_LANGUAGE":                      true,
		"DEFAULT_SCHEMA":                        true,
		"DELAYED_DURABILITY":                    true,
		"DENY":                                  true,
		"DIRECTORY_NAME":                        true,
		"DISABLE":                               true,
		"DISABLED":                              true,
		"DISABLE_BROKER":                        true,
		"DISK":                                  true,
		"DISTRIBUTED":                           true,
		"DUMP":                                  true,
		"DURABILITY":                            true,
		"ELEMENTS":                              true,
		"EMERGENCY":                             true,
		"ENABLE":                                true,
		"ENABLE_BROKER":                         true,
		"ENCRYPTED":                             true,
		"ENCRYPTION":                            true,
		"ENDPOINT":                              true,
		"ERRLVL":                                true,
		"ERROR_BROKER_CONVERSATIONS":            true,
		"ESCAPE":                                true,
		"EVENT":                                 true,
		"EVENTDATA":                             true,
		"EXCLUSIVE":                             true,
		"EXECUTABLE":                            true,
		"EXECUTE":                               true,
		"EXIT":                                  true,
		"EXPANDABLE":                            true,
		"FAST":                                  true,
		"FAST_FORWARD":                          true,
		"FETCH":                                 true,
		"FILE":                                  true,
		"FILEGROUP":                             true,
		"FILEGROWTH":                            true,
		"FILENAME":                              true,
		"FILESTREAM":                            true,
		"FILLFACTOR":                            true,
		"FILTER":                                true,
		"FIRST":                                 true,
		"FOLLOWING":                             true,
		"FORCE":                                 true,
		"FORCED":                                true,
		"FORCESEEK":                             true,
		"FORWARD_ONLY":                          true,
		"FREE":                                  true,
		"FULLSCAN":                              true,
		"FULLTEXT":                              true,
		"GB":                                    true,
		"GETDATE":                               true,
		"GETUTCDATE":                            true,
		"GO":                                    true,
		"GOVERNOR":                              true,
		"GROUP_MAX_REQUESTS":                    true,
		"HADR":                                  true,
		"HASH":                                  true,
		"HASHED":                                true,
		"HEALTHCHECKTIMEOUT":                    true,
		"HONOR_BROKER_PRIORITY":                 true,
		"HOURS":                                 true,
		"IDENTITY_INSERT":                       true,
		"IGNORE_CONSTRAINTS":                    true,
		"IGNORE_DUP_KEY":                        true,
		"IGNORE_NONCLUSTERED_COLUMNSTORE_INDEX": true,
		"IGNORE_TRIGGERS":                       true,
		"IMMEDIATE":                             true,
		"IMPERSONATE":                           true,
		"INCLUDE":                               true,
		"INCREMENT":                             true,
		"INCREMENTAL":                           true,
		"INFINITE":                              true,
		"INIT":                                  true,
		"INSENSITIVE":                           true,
		"INSERTED":                              true,
		"ISOLATION":                             true,
		"KB":                                    true,
		"KEEP":                                  true,
		"KEEPDEFAULTS":                          true,
		"KEEPFIXED":                             true,
		"KEEPIDENTITY":                          true,
		"KEY":                                   true,
		"KEYSET":                                true,
		"LANGUAGE":                              true,
		"LAST":                                  true,
		"LEVEL":                                 true,
		"LIBRARY":                               true,
		"LIFETIME":                              true,
		"LINKED":                                true,
		"LINUX":                                 true,
		"LISTENER":                              true,
		"LISTENER_URL":                          true,
		"LOB_COMPACTION":                        true,
		"LOCAL":                                 true,
		"LOCAL_SERVICE_NAME":                    true,
		"LOCK":                                  true,
		"LOCK_ESCALATION":                       true,
		"LOG":                                   true,
		"LOGIN":                                 true,
		"LOOP":                                  true,
		"MANUAL":                                true,
		"MARK":                                  true,
		"MASTER":                                true,
		"MAX":                                   true,
		"MAX_CPU_PERCENT":                       true,
		"MAX_DOP":                               true,
		"MAX_FILES":                             true,
		"MAX_MEMORY":                            true,
		"MAX_MEMORY_PERCENT":                    true,
		"MAX_PROCESSES":                         true,
		"MAX_QUEUE_READERS":                     true,
		"MAX_ROLLOVER_FILES":                    true,
		"MAXDOP":                                true,
		"MAXRECURSION":                          true,
		"MAXSIZE":                               true,
		"MB":                                    true,
		"MEDIUM":                                true,
		"MEMORY_OPTIMIZED":                      true,
		"MESSAGE":                               true,
		"MIN":                                   true,
		"MIN_ACTIVE_ROWVERSION":                 true,
		"MIN_CPU_PERCENT":                       true,
		"MIN_MEMORY_PERCENT":                    true,
		"MINUTES":                               true,
		"MIRROR":                                true,
		"MIRROR_ADDRESS":                        true,
		"MIXED_PAGE_ALLOCATION":                 true,
		"MODE":                                  true,
		"MODIFY":                                true,
		"MOVE":                                  true,
		"MULTI_USER":                            true,
		"NAME":                                  true,
		"NATIVE_COMPILATION":                    true,
		"NESTED_TRIGGERS":                       true,
		"NEW_BROKER":                            true,
		"NEWNAME":                               true,
		"NEXT":                                  true,
		"NO":                                    true,
		"NO_CHECKSUM":                           true,
		"NO_COMPRESSION":                        true,
		"NO_EVENT_LOSS":                         true,
		"NO_TRUNCATE":                           true,
		"NO_WAIT":                               true,
		"NOCOUNT":                               true,
		"NODES":                                 true,
		"NOEXPAND":                              true,
		"NON_TRANSACTED_ACCESS":                 true,
		"NORECOMPUTE":                           true,
		"NORECOVERY":                            true,
		"NOWAIT":                                true,
		"NTILE":                                 true,
		"NUMANODE":                              true,
		"NUMERIC_ROUNDABORT":                    true,
		"OBJECT":                                true,
		"OFFLINE":                               true,
		"OFFSET":                                true,
		"OLD_PASSWORD":                          true,
		"ONLINE":                                true,
		"ONLY":                                  true,
		"OPEN":                                  true,
		"OPEN_EXISTING":                         true,
		"OPENQUERY":                             true,
		"OPENROWSET":                            true,
		"OPENXML":                               true,
		"OPTIMISTIC":                            true,
		"OPTIMIZE":                              true,
		"OPTIMIZE_FOR_SEQUENTIAL_KEY":           true,
		"OPTION":                                true,
		"OUT":                                   true,
		"OUTPUT":                                true,
		"OWNER":                                 true,
		"OWNERSHIP":                             true,
		"PAGE":                                  true,
		"PAGECOUNT":                             true,
		"PARTITION":                             true,
		"PARTITIONS":                            true,
		"PASSWORD":                              true,
		"PATH":                                  true,
		"PERCENT":                               true,
		"PERCENTILE_CONT":                       true,
		"PERCENTILE_DISC":                       true,
		"PERMISSION_SET":                        true,
		"PERSISTED":                             true,
		"PILOT":                                 true,
		"PIVOT":                                 true,
		"PLAN":                                  true,
		"POLICY":                                true,
		"POOL":                                  true,
		"POPULATION":                            true,
		"PRECEDING":                             true,
		"PREDICATE":                             true,
		"PRIMARY_ROLE":                          true,
		"PRIOR":                                 true,
		"PRIORITY":                              true,
		"PRIORITY_LEVEL":                        true,
		"PRIVATE":                               true,
		"PRIVILEGES":                            true,
		"PROCESS":                               true,
		"PROFILE":                               true,
		"PROPERTY":                              true,
		"PROVIDER":                              true,
		"QUERY_STORE":                           true,
		"QUEUE":                                 true,
		"QUOTED_IDENTIFIER":                     true,
		"RAISERROR":                             true,
		"RANGE":                                 true,
		"RC2":                                   true,
		"RC4":                                   true,
		"RC4_128":                               true,
		"READ_COMMITTED_SNAPSHOT":               true,
		"READ_ONLY":                             true,
		"READ_WRITE":                            true,
		"READCOMMITTED":                         true,
		"READCOMMITTEDLOCK":                     true,
		"READONLY":                              true,
		"READPAST":                              true,
		"READUNCOMMITTED":                       true,
		"READWRITE":                             true,
		"REBUILD":                               true,
		"RECEIVE":                               true,
		"RECOMPILE":                             true,
		"RECOVERY":                              true,
		"RECURSIVE_TRIGGERS":                    true,
		"REGENERATE":                            true,
		"RELATED_CONVERSATION":                  true,
		"RELATED_CONVERSATION_GROUP":            true,
		"RELATIVE":                              true,
		"REMOTE":                                true,
		"REMOTE_PROC_TRANSACTIONS":              true,
		"REMOTE_SERVICE_NAME":                   true,
		"REMOVE":                                true,
		"REORGANIZE":                            true,
		"REPEATABLE":                            true,
		"REPEATABLEREAD":                        true,
		"REPLACE":                               true,
		"REPLICA":                               true,
		"REPLICATE":                             true,
		"REQUEST_MAX_CPU_TIME_SEC":              true,
		"REQUEST_MAX_MEMORY_GRANT_PERCENT":      true,
		"REQUEST_MEMORY_GRANT_TIMEOUT_SEC":      true,
		"REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT": true,
		"RESAMPLE":                         true,
		"RESET":                            true,
		"RESTART":                          true,
		"RESTORE":                          true,
		"RESTRICT_GEOM_SPEC_TO_REGIONATOR": true,
		"RESTRICTED_USER":                  true,
		"RESUMABLE":                        true,
		"RETENTION":                        true,
		"RETURN":                           true,
		"RETURNS":                          true,
		"REVERT":                           true,
		"ROLLBACK":                         true,
		"ROUTE":                            true,
		"ROW":                              true,
		"ROWCOUNT":                         true,
		"ROWGUID":                          true,
		"ROWGUIDCOL":                       true,
		"ROWS":                             true,
		"ROWS_PER_BATCH":                   true,
		"RSA_1024":                         true,
		"RSA_2048":                         true,
		"RSA_3072":                         true,
		"RSA_4096":                         true,
		"RSA_512":                          true,
		"SAFETY":                           true,
		"SAFE":                             true,
		"SAMPLE":                           true,
		"SAVE":                             true,
		"SCHEDULER":                        true,
		"SCHEMA_ID":                        true,
		"SCHEMA_NAME":                      true,
		"SCHEMABINDING":                    true,
		"SCOPE":                            true,
		"SCROLL":                           true,
		"SCROLL_LOCKS":                     true,
		"SEARCH":                           true,
		"SECONDS":                          true,
		"SECONDARY":                        true,
		"SECONDARY_ONLY":                   true,
		"SECONDARY_ROLE":                   true,
		"SECURITY":                         true,
		"SECURITY_LOG":                     true,
		"SECURITYAUDIT":                    true,
		"SELECTIVE":                        true,
		"SELF":                             true,
		"SEND":                             true,
		"SENT":                             true,
		"SERIALIZABLE":                     true,
		"SERVER":                           true,
		"SERVICE":                          true,
		"SERVICE_BROKER":                   true,
		"SERVICE_NAME":                     true,
		"SESSION":                          true,
		"SESSION_TIMEOUT":                  true,
		"SETERROR":                         true,
		"SETS":                             true,
		"SETTINGS":                         true,
		"SHOWPLAN":                         true,
		"SHOWPLAN_ALL":                     true,
		"SHOWPLAN_TEXT":                    true,
		"SHOWPLAN_XML":                     true,
		"SHRINKLOG":                        true,
		"SHUTDOWN":                         true,
		"SID":                              true,
		"SIGNATURE":                        true,
		"SIMPLE":                           true,
		"SINGLE_USER":                      true,
		"SIZE":                             true,
		"SNAPSHOT":                         true,
		"SORT_IN_TEMPDB":                   true,
		"SOURCE":                           true,
		"SPARSE":                           true,
		"SPATIAL":                          true,
		"SPECIFICATION":                    true,
		"SPLIT":                            true,
		"SQL":                              true,
		"SQLDUMPERFLAGS":                   true,
		"SQLDUMPERUSERDUMPS":               true,
		"SQLDUMPERSETUPFLAGS":              true,
		"STANDBY":                          true,
		"START":                            true,
		"START_DATE":                       true,
		"STARTED":                          true,
		"STARTUP_STATE":                    true,
		"STATE":                            true,
		"STATIC":                           true,
		"STATISTICAL_SEMANTICS":            true,
		"STATISTICS":                       true,
		"STATISTICS_INCREMENTAL":           true,
		"STATISTICS_NORECOMPUTE":           true,
		"STATS":                            true,
		"STATS_STREAM":                     true,
		"STATUS":                           true,
		"STATUSONLY":                       true,
		"STOP":                             true,
		"STOPLIST":                         true,
		"STOPPED":                          true,
		"STRING_AGG":                       true,
		"SUBJECT":                          true,
		"SUBSCRIPTION":                     true,
		"SUPPORTED":                        true,
		"SUSPEND":                          true,
		"SWITCH":                           true,
		"SYMMETRIC":                        true,
		"SYNCHRONOUS_COMMIT":               true,
		"SYNONYM":                          true,
		"SYSTEM":                           true,
		"TAKE":                             true,
		"TARGET":                           true,
		"TARGET_RECOVERY_TIME":             true,
		"TB":                               true,
		"TEXTSIZE":                         true,
		"THROW":                            true,
		"TIES":                             true,
		"TIME":                             true,
		"TIMEOUT":                          true,
		"TIMER":                            true,
		"TOP":                              true,
		"TORN_PAGE_DETECTION":              true,
		"TRACK_CAUSALITY":                  true,
		"TRANSFER":                         true,
		"TRANSFORM_NOISE_WORDS":            true,
		"TRIPLE_DES":                       true,
		"TRIPLE_DES_3KEY":                  true,
		"TRUSTWORTHY":                      true,
		"TRY":                              true,
		"TSQL":                             true,
		"TWO_DIGIT_YEAR_CUTOFF":            true,
		"TYPE":                             true,
		"TYPE_WARNING":                     true,
		"UNBOUNDED":                        true,
		"UNCOMMITTED":                      true,
		"UNCHECKED":                        true,
		"UNDEFINED":                        true,
		"UNLIMITED":                        true,
		"UNMASK":                           true,
		"UNPIVOT":                          true,
		"UNSAFE":                           true,
		"URL":                              true,
		"USAGE":                            true,
		"USE":                              true,
		"USED":                             true,
		"USER_OPTIONS":                     true,
		"VALIDATION":                       true,
		"VALUE":                            true,
		"VIEWS":                            true,
		"WAIT":                             true,
		"WAITFOR":                          true,
		"WELL_FORMED_XML":                  true,
		"WINDOWS":                          true,
		"WITHOUT":                          true,
		"WITNESS":                          true,
		"WORK":                             true,
		"WORKLOAD":                         true,
		"XML":                              true,
		"XMLNAMESPACES":                    true,
		"XSINIL":                           true,
		"ZONE":                             true,
	}
)
